### ISSUE TITLE
Run Kubeflow Pipelines No Host Specified Error

### ISSUE THREAD

**Issue by eletonia** [elyra-ai/elyra#1067]
I am seeing this error when after clicking `Run Pipeline` and choosing my local Kubeflow Pipeline runtime config.
What host do I need to specify and where do I specify it? 

This is my runtime configuration for Kubeflow Pipelines:
<img width="365" alt="Screen Shot 2020-11-12 at 11 21 37 AM" src="https://user-images.githubusercontent.com/6710338/98966405-3de73d80-24d9-11eb-9759-7e1d24da2e65.png">

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/usr/local/lib/python3.8/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/usr/local/lib/python3.8/site-packages/elyra/pipeline/processor.py", line 70, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 100, in process
    raise lve
  File "/usr/local/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 89, in process
    client.upload_pipeline(pipeline_path,
  File "/usr/local/lib/python3.8/site-packages/kfp/_client.py", line 720, in upload_pipeline
    response = self._upload_api.upload_pipeline(pipeline_package_path, name=pipeline_name, description=description)
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 83, in upload_pipeline
    return self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 177, in upload_pipeline_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 378, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 195, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 421, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 279, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 196, in request
    r = self.pool_manager.request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 325, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 231, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
```

**Comment by ptitzler** [comment]
Try specifying `127.0.0.1` instead of `localhost` in your runtime environment configuration.

**Comment by eletonia** [comment]
That worked, thank you!

**Comment by ptitzler** [comment]
Great! My understanding is that `localhost` used to work in the past, but I don't believe anybody has had a chance to investigate what has changed under the covers that is causing the new behavior.

**Comment by ptitzler** [comment]
The root cause is likely a bug in `kfp`. We currently require version `1.0.0` of that package. An upgrade to 1.0.1+ should likely also resolve the issue and `localhost` should work again.

**Comment by ptitzler** [comment]
Confirmed this using a simple connectivity test using `kfp.Client(host='http://localhost:32235/pipeline')`. With `kfp==1.0.0` connectivity cannot be established due to `LocationValueError("No host specified.")`, whereas `kfp==1.1.0` yields the expected result.
