### ISSUE TITLE
Watch mode throws error

### ISSUE THREAD

**Issue by marthacryan** [elyra-ai/elyra#1175]
To duplicate:
run `make watch` and `jupyter lab --watch`

Error shows up in JupyterLab log under `[I 2021-01-05 11:28:30.293 ServerApp] nbclassic | extension was successfully loaded.`:
```
node:internal/fs/utils:320
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/@elyra/python-editor-extension/src/index.ts'
    at Object.statSync (node:fs:1128:3)
    at Object.statSync (/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/graceful-fs/polyfills.js:308:16)
    at maybeSync (/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/webpack.config.js:110:20)
    at /Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/webpack.config.js:153:7
    at Array.some (<anonymous>)
    at ignored (/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/webpack.config.js:144:24)
    at Array.filter (<anonymous>)
    at FilterIgnoringWatchFileSystem.watch (/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/@jupyterlab/builder/lib/webpack-plugins.js:76:40)
    at Watching.watch (/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:221:48)
    at /Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:198:13 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/@elyra/python-editor-extension/src/index.ts'
}
```

Running `ls /Users/martha.cryanibm.com/opt/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/@elyra/python-editor-extension/` outputs:
`lib, package.json, style`

**Comment by marthacryan** [comment]
@ajbozarth Any ideas?
