### ISSUE TITLE
Resuse stop working after a few seconds

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1227]
**Describe the issue**
Start JupyterLab, and look for memory usage on the status bar... 
After a few seconds, it disappears, and the following start being shown on the server log

```
[E 2021-01-21 22:07:00.812 ServerApp] Uncaught exception GET /api/metrics/v1?1611295620798 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/metrics/v1?1611295620798', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_common.py", line 447, in wrapper
        ret = self._cache[fun]
    AttributeError: 'Process' object has no attribute '_cache'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_common.py", line 447, in wrapper
        ret = self._cache[fun]
    AttributeError: _cache
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 365, in catch_zombie
        yield
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 406, in _get_pidtaskinfo
        ret = cext.proc_pidtaskinfo_oneshot(self.pid)
    ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyter_resource_usage/api.py", line 31, in get
        rss = sum([p.memory_info().rss for p in all_processes])
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyter_resource_usage/api.py", line 31, in <listcomp>
        rss = sum([p.memory_info().rss for p in all_processes])
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_common.py", line 450, in wrapper
        return fun(self)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/__init__.py", line 1054, in memory_info
        return self._proc.memory_info()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 344, in wrapper
        return fun(self, *args, **kwargs)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 475, in memory_info
        rawtuple = self._get_pidtaskinfo()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 344, in wrapper
        return fun(self, *args, **kwargs)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_common.py", line 450, in wrapper
        return fun(self)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 406, in _get_pidtaskinfo
        ret = cext.proc_pidtaskinfo_oneshot(self.pid)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/psutil/_psosx.py", line 376, in catch_zombie
        raise ZombieProcess(proc.pid, proc._name, proc._ppid)
    psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=69880)
```

**Comment by ajbozarth** [comment]
As far as I can tell this will be fixed by this PR on psutil https://github.com/giampaolo/psutil/pull/1903 which should be automatically picked up once it's released. We can leave this issue open to track the progress of the fix

**Comment by lresende** [comment]
Is this still reproducible?

**Comment by lresende** [comment]
I don't seem to be able to reproduce this anymore.
