### ISSUE TITLE
MetadataDisplay.renderMetadata throws TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1307]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create a runtime configuration leaving the UI endpoint URL property empty
2. Save and close.
3. The manage runtime configuration widget disappears.
4. See error messages in browser's console log.

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Sending a GET request to http://localhost:8888/elyra/metadata/runtimes
static/lab/vendors-node_modules_elyra_pipeline-editor-extension_lib_index_js.cb6a6ea07e1a82d7954c.js:2514 Uncaught TypeError: Cannot read property 'endsWith' of undefined
    at RuntimesDisplay.renderExpandableContent (static/lab/vendors-node_modules_elyra_pipeline-editor-extension_lib_index_js.cb6a6ea07e1a82d7954c.js:2514)
    at MetadataDisplay.renderMetadata (static/lab/vendors-node_modules_elyra_metadata-common_lib_index_js.3d940acea80065cf5c8e.js:878)
    at Array.map (<anonymous>)
    at RuntimesDisplay.render (static/lab/vendors-node_modules_elyra_metadata-common_lib_index_js.3d940acea80065cf5c8e.js:989)
    at finishClassComponent (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:17595)
    at updateClassComponent (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:17545)
    at beginWork (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:19183)
    at HTMLUnknownElement.callCallback (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4055)
    at Object.invokeGuardedCallbackDev (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4104)
    at invokeGuardedCallback (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4166)
static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:20195 The above error occurred in the <RuntimesDisplay> component:

    at RuntimesDisplay (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor-extension_lib_index_js.cb6a6ea07e1a82d7954c.js:2512:1)
    at UseSignal (http://localhost:8888/static/lab/jlab_core.eae47d45daaf5ab43e71.js:10677:9)
    at div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:20195
static/lab/jlab_core.eae47d45daaf5ab43e71.js:114561 TypeError: Cannot read property 'endsWith' of undefined
    at RuntimesDisplay.renderExpandableContent (static/lab/vendors-node_modules_elyra_pipeline-editor-extension_lib_index_js.cb6a6ea07e1a82d7954c.js:2514)
    at MetadataDisplay.renderMetadata (static/lab/vendors-node_modules_elyra_metadata-common_lib_index_js.3d940acea80065cf5c8e.js:878)
    at Array.map (<anonymous>)
    at RuntimesDisplay.render (static/lab/vendors-node_modules_elyra_metadata-common_lib_index_js.3d940acea80065cf5c8e.js:989)
    at finishClassComponent (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:17595)
    at updateClassComponent (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:17545)
    at beginWork (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:19183)
    at HTMLUnknownElement.callCallback (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4055)
    at Object.invokeGuardedCallbackDev (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4104)
    at invokeGuardedCallback (static/lab/vendors-node_modules_react-dom_index_js.a188b39e2c70c7b15b90.js:4166)
Private.exceptionHandler @ static/lab/jlab_core.eae47d45daaf5ab43e71.js:114561
static/lab/vendors-node_modules_elyra_services_lib_index_js.f0b5f6f7325d0b600e49.js:424 Sending a GET request to http://localhost:8888/elyra/metadata/runtimes
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.x
 - Operating system: macos
 - Installation source: from source
 - Deployment type:  local installation

**Comment by ptitzler** [comment]
- The only way to get the widget to display again is through the command palette.
- Also noticed that all entries are now displayed as a JSON dump, and not formatted:
  ![image](https://user-images.githubusercontent.com/13068832/108418800-8f911980-71e6-11eb-80ac-bc332b1a1818.png)
 No idea if this is related to the failure above or not.

**Comment by ptitzler** [comment]
The problem should no longer be re-creatable after https://github.com/elyra-ai/elyra/issues/1278 was delivered.

**Comment by ptitzler** [comment]
The endpoint URL is now a required field and the issue can therefore no longer be encountered.
