### ISSUE TITLE
No details provided to user when pipeline runtime server is down

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1322]
User Interface:
![image](https://user-images.githubusercontent.com/382917/108752352-33850880-74f8-11eb-9115-96aa1adc294f.png)

JupyterLab log:
```
[E 2021-02-22 10:21:55.536 ServerApp] Error uploading artifacts to object storage for operation: python-linregr-least-squares-fit
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 61] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
        chunked=chunked,
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/http/client.py", line 1277, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/http/client.py", line 1323, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/http/client.py", line 1272, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/http/client.py", line 1032, in _send_output
        self.send(msg)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/http/client.py", line 972, in send
        self.connect()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
        conn = self._new_conn()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
        self, "Failed to establish a new connection: %s" % e
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f94a01cb750>: Failed to establish a new connection: [Errno 61] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 218, in _upload_dependencies_to_object_store
        cos_client = CosClient(config=runtime_configuration)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 41, in __init__
        self.client = self.__initialize_object_store()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 53, in __initialize_object_store
        if not self.client.bucket_exists(self.bucket):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 404, in bucket_exists
        self._url_open('HEAD', bucket_name=bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2189, in _url_open
        region = self._get_bucket_region(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2067, in _get_bucket_region
        region = self._get_bucket_location(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2102, in _get_bucket_location
        headers=headers)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      [Previous line repeated 2 more times]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='coffined1.fyre.ibm.com', port=32406): Max retries exceeded with url: /covid?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94a01cb750>: Failed to establish a new connection: [Errno 61] Connection refused'))
[E 2021-02-22 10:21:55.538 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1614018108888 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1614018108888', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 75, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 72, in process
        pipeline_name=pipeline_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 257, in create_pipeline_file
        notebook_ops = self._cc_pipeline(pipeline, pipeline_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 220, in _cc_pipeline
        operation)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 238, in _upload_dependencies_to_object_store
        raise ex from ex
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 218, in _upload_dependencies_to_object_store
        cos_client = CosClient(config=runtime_configuration)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 41, in __init__
        self.client = self.__initialize_object_store()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 53, in __initialize_object_store
        if not self.client.bucket_exists(self.bucket):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 404, in bucket_exists
        self._url_open('HEAD', bucket_name=bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2189, in _url_open
        region = self._get_bucket_region(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2067, in _get_bucket_region
        region = self._get_bucket_location(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2102, in _get_bucket_location
        headers=headers)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      [Previous line repeated 2 more times]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='coffined1.fyre.ibm.com', port=32406): Max retries exceeded with url: /covid?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94a01cb750>: Failed to establish a new connection: [Errno 61] Connection refused'))
[E 2021-02-22 10:21:55.539 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 75, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 72, in process
        pipeline_name=pipeline_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 257, in create_pipeline_file
        notebook_ops = self._cc_pipeline(pipeline, pipeline_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor_airflow.py", line 220, in _cc_pipeline
        operation)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 238, in _upload_dependencies_to_object_store
        raise ex from ex
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 218, in _upload_dependencies_to_object_store
        cos_client = CosClient(config=runtime_configuration)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 41, in __init__
        self.client = self.__initialize_object_store()
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/cos.py", line 53, in __initialize_object_store
        if not self.client.bucket_exists(self.bucket):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 404, in bucket_exists
        self._url_open('HEAD', bucket_name=bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2189, in _url_open
        region = self._get_bucket_region(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2067, in _get_bucket_region
        region = self._get_bucket_location(bucket_name)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/minio/api.py", line 2102, in _get_bucket_location
        headers=headers)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/poolmanager.py", line 336, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 767, in urlopen
        **response_kw
      [Previous line repeated 2 more times]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='coffined1.fyre.ibm.com', port=32406): Max retries exceeded with url: /covid?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94a01cb750>: Failed to establish a new connection: [Errno 61] Connection refused'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/web.py", line 1217, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/elyra/util/http.py", line 75, in write_error
        self.set_status(status_code, reason=reply['reason'])
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/web.py", line 358, in set_status
        self._reason = escape.native_str(reason)
      File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/tornado/escape.py", line 228, in to_unicode
        raise TypeError("Expected bytes, unicode, or None; got %r" % type(value))
    TypeError: Expected bytes, unicode, or None; got <class 'urllib3.exceptions.NewConnectionError'>
[E 2021-02-22 10:21:55.540 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "808",
      "Sec-Ch-Ua": "\"Chromium\";v=\"88\", \"Google Chrome\";v=\"88\", \";Not A Brand\";v=\"99\"",
      "Authorization": "token 5089bb77064c33e902129036c9ebe9a7847e9f05eebafb2a",
      "X-Xsrftoken": "2|941cd255|26c88db9985751a986682ab99424e2d2|1614017000",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/demo/python-linregr-least-squares-fit.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7",
      "Cookie": "_xsrf=2|941cd255|26c88db9985751a986682ab99424e2d2|1614017000; username-localhost-8888=\"2|1:0|10:1614018106|23:username-localhost-8888|44:YjM1ZTA2NWM2MGQwNDhmNmJlN2NiMzczMDljNTcxZGQ=|ab31ea9fca685bb08e01eba96c4ae12d2a58a22e66181b837e650185c0682154\""
    }
```

**Comment by ptitzler** [comment]
Slightly off-topic, but I wouldn't expect a response from a server named `coffined`. 😉

**Comment by akchinSTC** [comment]
This issue under the covers is actually the same as #1376 both involve the inability to connect to the cos endpoint.  
Pull request #1377 should resolve both issues
