### ISSUE TITLE
Watch mode is failing

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#1338]
**Describe the issue**
The watch mode on Elyra fails to pick up code changes

**To Reproduce**
1. build from master with `make clean install`
2. run `make watch`
3. On another terminal, run `jupyter lab --watch`
4. make any change to one of the ts files and save it
5. check the terminal running `make watch` for file change detection msg and make sure there are no compilation errors
5. reload jupyterlab page and try to access your code change
6. The page doesn't pick up the changes (eg. inspecting the file still shows the original code version)
7. Check for errors on the serverapp

**Screenshots or log output**
<details><summary>Error log</summary>
<pre>
/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/@jupyterlab/builder/lib/webpack-plugins.js:93
                    const dirTimestamps = watcher.getContextInfoEntries();
                                                  ^
TypeError: watcher.getContextInfoEntries is not a function
    at Object.getContextTimeInfoEntries (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/@jupyterlab/builder/lib/webpack-plugins.js:93:51)
    at run (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:94:48)
    at /Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:75:6
    at /Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.endIdle (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Cache.js:140:22)
    at run (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:72:32)
    at Watching._go (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:152:3)
    at Watching._invalidate (/Users/kspuldaro/miniconda3/envs/dev/share/jupyter/lab/staging/node_modules/webpack/lib/Watching.js:320:9)
error Command failed with exit code 1.
</pre>
</details>

**Expected behavior**
When running jupyterlab in watch mode, it should pick up code changes on page reload

**Comment by ajbozarth** [comment]
I can confirm I am also seeing this error when jupyterlab "rebuilds" after I make changes

**Comment by ajbozarth** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/9915 to address this issue

**Comment by ajbozarth** [comment]
Fix has been merged to lab and back ported, will be available upon next release

**Comment by jasongrout** [comment]
> Fix has been merged to lab and back ported, will be available upon next release

It is now published in JLab 3.0.10.

**Comment by ajbozarth** [comment]
thanks for the quick patch release, tested it and it works
