### ISSUE TITLE
Bump kfp-tekton dependency to fix pyyaml transitive not being updated

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#1383]
**Describe the issue**
In a new python env, installing elyra 2.1.0rc1, the pyyaml package is not updated to v5+, but instead remains at 3.x while is insufficient for the kfp-tekton compiler. 

**To Reproduce**
1. on a new ubuntu linux v18 system, installed python3 from apt, not conda
2. pip3 install elyra --pre
3. pip3 list installed | grep pyyaml
4. Attempt to run or compile a kfp pipeline in with the tekton engine

**Screenshots or log output**

![image](https://user-images.githubusercontent.com/13340013/110385928-707eee00-8014-11eb-8553-526b884e5f1d.png)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elyra/pipeline/processor_kfp.py", line 134, in process
    kfp_tekton.compiler.TektonCompiler().compile(pipeline_function, pipeline_path)
  File "/usr/local/lib/python3.6/dist-packages/kfp_tekton/compiler/compiler.py", line 740, in compile
    super().compile(pipeline_func, package_path, type_check, pipeline_conf=pipeline_conf)
  File "/usr/local/lib/python3.6/dist-packages/kfp/compiler/compiler.py", line 951, in compile
    package_path=package_path)
  File "/usr/local/lib/python3.6/dist-packages/kfp_tekton/compiler/compiler.py", line 839, in _create_and_write_workflow
    TektonCompiler._write_workflow(workflow=workflow, package_path=package_path)   # Tekton change
  File "/usr/local/lib/python3.6/dist-packages/kfp_tekton/compiler/compiler.py", line 798, in _write_workflow
    yaml_text = dump_yaml(_handle_tekton_pipeline_variables(yaml.load(yaml_text, Loader=yaml.FullLoader)))
AttributeError: module 'yaml' has no attribute 'FullLoader'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.6/dist-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/usr/local/lib/python3.6/dist-packages/elyra/pipeline/processor.py", line 75, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elyra/pipeline/processor_kfp.py", line 139, in process
    format(pipeline_name, engine, pipeline_path), str(ex)) from ex
RuntimeError: ('Error compiling pipeline untitled for engine Tekton at /tmp/tmptgv5to8c/untitled.tar.gz', "module 'yaml' has no attribute 'FullLoader'")
Check the JupyterLab log for more details at 2021-03-08 16:58:38


```

**Expected behavior**
Pipeline to compile successfully and either produce an exported file or submitted pipeline

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1.0 rc1
 - Operating system: linux - ubuntu 18
 - Installation source: pypi
 - Deployment type: local

**Comment by akchinSTC** [comment]
Did some digging and looks like kfp==1.3.0 is supposed to bump pyyaml to v5+, doesn't actually do it, so when kfp-tekton compiler is called there is a library mismatch. 
I would like to take the less intrusive route and add a pyyaml==5.3.1 requirement to our requirements as a stopgap, since we bumping to kfp-tekton 0.7.0 would require us to update to kfp==1.4.0 as well which we have not tested against.
