### ISSUE TITLE
 R script processing fails execution on Apache Airflow

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1538]
**Describe the issue**
See below. Looks like R scripts in general are not yet supported on AA.

**To Reproduce**
1. Create an R script. 
2. Create an Apache Airflow RTC
3. Submit the R script using above RTC
4. Check the task log file

```
[2021-04-08 20:58:24,774] {pod_launcher.py:156} INFO - b"[I 20:58:24.773] 'an_r_script-0408135736':'an_r_script' - Packages installed (13.682 secs)\n"
[2021-04-08 20:58:24,779] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-04-08 20:58:24,780] {pod_launcher.py:156} INFO - b'  File "bootstrapper.py", line 395, in <module>\n'
[2021-04-08 20:58:24,780] {pod_launcher.py:156} INFO - b'    main()\n'
[2021-04-08 20:58:24,780] {pod_launcher.py:156} INFO - b'  File "bootstrapper.py", line 384, in main\n'
[2021-04-08 20:58:24,780] {pod_launcher.py:156} INFO - b'    file_op = FileOpBase.get_instance(**input_params)\n'
[2021-04-08 20:58:24,781] {pod_launcher.py:156} INFO - b'  File "bootstrapper.py", line 57, in get_instance\n'
[2021-04-08 20:58:24,781] {pod_launcher.py:156} INFO - b"    raise ValueError('Unsupported file type: {}'.format(filepath))\n"
[2021-04-08 20:58:24,781] {pod_launcher.py:156} INFO - b'ValueError: Unsupported file type: an_r_script.r\n'
[2021-04-08 20:58:25,822] {pod_launcher.py:173} INFO - Event: an-r-script-1ed4d6271f374226a7abe2fa51b94fb6 had an event of type Failed
[2021-04-08 20:58:25,822] {pod_launcher.py:284} INFO - Event with job id an-r-script-1ed4d6271f374226a7abe2fa51b94fb6 Failed
[2021-04-08 20:58:25,839] {pod_launcher.py:173} INFO - Event: an-r-script-1ed4d6271f374226a7abe2fa51b94fb6 had an event of type Failed
[2021-04-08 20:58:25,839] {pod_launcher.py:284} INFO - Event with job id an-r-script-1ed4d6271f374226a7abe2fa51b94fb6 Failed
[2021-04-08 20:58:25,863] {taskinstance.py:1150} ERROR - Pod Launching failed: Pod returned a failure: failed
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 287, in execute
    'Pod returned a failure: {state}'.format(state=final_state))
airflow.exceptions.AirflowException: Pod returned a failure: failed
```

**Expected behavior**
The R script is executed.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2+
 - Installation source: from source
 - Deployment type: local execution

**Comment by lresende** [comment]
There are a few missing updates to airflow, which are ready to be tested/merged on this pr: https://github.com/elyra-ai/airflow-notebook/pull/4

**Comment by akchinSTC** [comment]
pulling and testing the updates now

**Comment by akchinSTC** [comment]
![image](https://user-images.githubusercontent.com/13340013/114115097-05d10480-9897-11eb-9caf-db8f66eed32b.png)
Prelim tests look good.

**Comment by ptitzler** [comment]
@akchinSTC can you please indicate which version of the `kf-notebook` container image includes the fix?
