### ISSUE TITLE
Invalid COS credentials trigger user cryptic exception

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1568]
**Describe the issue**
See next section. The root cause (invalid credentials) repesents a common [user] error scenario.

**To Reproduce**
1. Create a notebook
2. Create a pipeline and add the notebook
3. Create a KFP runtime configuration with invalid COS user credentials (e.g. wrong password)
4. Export or run pipeline using that runtime configuration

![image](https://user-images.githubusercontent.com/13068832/114771018-f4697b80-9d20-11eb-8b37-86756c9f0087.png)

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
[I 2021-04-14 12:46:25.882 ServerApp] kfp 'untitled':'Untitled' - processing operation dependencies for id: 431db185-d660-4035-8c53-4e2cea22fd88 
[I 2021-04-14 12:46:25.884 ServerApp] kfp 'untitled-0414124625':'Untitled' - generated dependency archive: /var/folders/h8/l3qh8v192rv_vvggc6wyphzc0000gn/T/elyra/Untitled-431db185-d660-4035-8c53-4e2cea22fd88.tar.gz (0.002 secs)
[E 2021-04-14 12:46:26.192 ServerApp] Error uploading artifacts to object storage for operation: Untitled
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 281, in _upload_dependencies_to_object_store
        cos_client = CosClient(config=runtime_configuration)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/util/cos.py", line 41, in __init__
        self.client = self.__initialize_object_store()
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/util/cos.py", line 53, in __initialize_object_store
        if not self.client.bucket_exists(self.bucket):
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 404, in bucket_exists
        self._url_open('HEAD', bucket_name=bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2189, in _url_open
        region = self._get_bucket_region(bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2067, in _get_bucket_region
        region = self._get_bucket_location(bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2109, in _get_bucket_location
        raise ResponseError(response, method, bucket_name).get_exception()
    minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.
[E 2021-04-14 12:46:26.198 ServerApp] Uncaught exception POST /elyra/pipeline/export?1618429585839 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/export?1618429585839', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 54, in post
        pipeline_overwrite
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 89, in export
        None, processor.export, pipeline, pipeline_export_format, pipeline_export_path, overwrite)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 291, in export
        export=True)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 452, in _cc_pipeline
        operation)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 306, in _upload_dependencies_to_object_store
        raise ex from ex
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 281, in _upload_dependencies_to_object_store
        cos_client = CosClient(config=runtime_configuration)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/util/cos.py", line 41, in __init__
        self.client = self.__initialize_object_store()
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/elyra/util/cos.py", line 53, in __initialize_object_store
        if not self.client.bucket_exists(self.bucket):
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 404, in bucket_exists
        self._url_open('HEAD', bucket_name=bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2189, in _url_open
        region = self._get_bucket_region(bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2067, in _get_bucket_region
        region = self._get_bucket_location(bucket_name)
      File "/opt/anaconda3/envs/elyra_dev/lib/python3.7/site-packages/minio/api.py", line 2109, in _get_bucket_location
        raise ResponseError(response, method, bucket_name).get_exception()
    minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.
[E 2021-04-14 12:46:26.204 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "1624",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
      "Authorization": "token 54fdbd55651e6be3454e2cae9bbbcd6732fe6882f28def3d",
      "X-Xsrftoken": "2|3a5f00dd|c99ae0c73961a332e03c47f4c49cdcdd|1618416193",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/untitled.pipeline",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8",
      "Cookie": "_xsrf=2|3a5f00dd|c99ae0c73961a332e03c47f4c49cdcdd|1618416193; username-localhost-8888=\"2|1:0|10:1618429585|23:username-localhost-8888|44:MWYzOGNmNmIxNDYwNDIyNDgwODZiMThlODhlZjA5N2Y=|64be00a6fdf8d488349d9738d931dc40385cda5c581bfa58bec1d747f0e516b1\""
    }
[E 2021-04-14 12:46:26.204 ServerApp] 500 POST /elyra/pipeline/export?1618429585839 (::1) 362.06ms referer=http://localhost:8888/lab/tree/untitled.pipeline

</pre>
</details>

**Expected behavior**

- https://github.com/elyra-ai/elyra/blob/master/elyra/util/cos.py#L61 should be caught in https://github.com/elyra-ai/elyra/blob/master/elyra/pipeline/processor.py#L273-L306
- A user friendly message should be displayed/logged, indicating that the credentials are a likely cause of this issue. (Note that a web search for this error yields results that seem to indicate that there are different reasons why this specific error is raised. )

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.1+
 - Installation source: from source
 - Deployment type: local installation

**Comment by kevin-bates** [comment]
> (Note that a web search for this error yields results that seem to indicate that there are different reasons why this specific error is raised. )

Are you suggesting that we treat all `ResponseError` instances as credential-related or that, after interrogating the `ResponseError` we treat all `SignatureDoesNotMatch` (internal) instances as credential-related?  It's tough to determine which _specific error_ you're referring to.  I think the former is more of a generic exception while the latter could probably be classified as credential-related and suspect you're referring to `SignatureDoesNotMatch`.

**Comment by ptitzler** [comment]
> and suspect you're referring to SignatureDoesNotMatch.

Yes, it's that one I was eluding to. Looking at the scenarios that can trigger an exception that is bubbled up ...
```
        self.client = Minio(endpoint=self.endpoint.netloc,
                            access_key=self.access_key,
                            secret_key=self.secret_key,
                            secure=self.secure)

        # Make a bucket with the make_bucket API call.
        try:
            if not self.client.bucket_exists(self.bucket):
                self.client.make_bucket(self.bucket)
```
- the Minio constructor won't surface any issues because it doesn't seem to perform any validation
- `bucket_exists` will surface host/port issues through `MaxRetryError`
- `bucket_exists` surfaces credential issues through `ResponseError`/`minio.error.SignatureDoesNotMatch`
- `make_bucket` surfaces bucket existence/permission issues through means other than `SignatureDoesNotMatch`

Therefore I believe it should be okay to interpret/surface `SignatureDoesNotMatch` errors as credential issues unless somebody can identify other scenarios that would cause  `bucket_exists` and `make_bucket` to also raise this exception.
