### ISSUE TITLE
KFP component export processing: 'TaskSpec' object has no attribute 'classifier'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1756]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create a KFP RTC
1. Create a KFP pipeline
3. Add the WML deployment sample component
4. Configure required values with dummies (the failure occurs before the pipeline is run, hence the value does not matter)
5. Export pipeline

<pre>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/rc_testing/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/anaconda3/envs/rc_testing/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 56, in post
    pipeline_overwrite
  File "/opt/anaconda3/envs/rc_testing/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 100, in export
    None, processor.export, pipeline, pipeline_export_format, pipeline_export_path, overwrite)
  File "/opt/anaconda3/envs/rc_testing/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/rc_testing/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 316, in export
    if operation.classifier not in ["execute-notebook-node", "execute-python-node", "execute-r-node"]:
AttributeError: 'TaskSpec' object has no attribute 'classifier'
</pre>

**Comment by kiersten-stokes** [comment]
As it turns out, this issue applies to all non-generic components. Looks like I'll have to make additional changes to the KFP-export jinja template in order to account for new components' structure.

**Comment by kiersten-stokes** [comment]
So after looking into this a bit more, there are some larger problems related to exporting to KFP Python DSL than initially thought. Non-generic components are rendered as `TaskSpec` objects, and the DSL throws an error at the `op.after` function in `processor_kfp.py:504`, even though the same function succeeds when run during the 'submit' process.

This is related to [#1760](https://github.com/elyra-ai/elyra/issues/1760#issuecomment-861715725).

**Comment by ptitzler** [comment]
See https://github.com/elyra-ai/elyra/issues/2301 for an explanation
