### ISSUE TITLE
KFP components throw error when processing parent operations during Python DSL export

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#1760]
**Describe the issue**
When chaining non-generic KFP components, an error is thrown in `processor_kfp.py` line 511, citing `AttributeError: 'ComponentReference' object has no attribute 'after'`. Digging into this a bit further, it's clear that the factory function that is the result of loading a component is actually a KFP `TaskSpec` object and not a `ContainerOp` object like the generic components are.

**To Reproduce**
1. Create a KFP pipeline and chain 2+ non-generic operators
2. Click on export or submit
3. See error

**Screenshots or log output**
<details><summary>Log Output</summary>
<pre>
    Traceback (most recent call last):
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/elyra/pipeline/processor_kfp.py", line 506, in _cc_pipeline
        op.after(parent_op)
    AttributeError: 'TaskSpec' object has no attribute 'after'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/elyra/pipeline/handlers.py", line 52, in post
        pipeline_exported_path = await PipelineProcessorManager.instance().export(
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 99, in export
        res = await asyncio.get_event_loop().run_in_executor(
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/elyra/pipeline/processor_kfp.py", line 306, in export
        defined_pipeline = self._cc_pipeline(pipeline,
      File "/Users/kierstenstokes/miniconda3/envs/dev1/lib/python3.9/site-packages/elyra/pipeline/processor_kfp.py", line 508, in _cc_pipeline
        op.component_ref.after(parent_op)
    AttributeError: 'ComponentReference' object has no attribute 'after'</pre>
</details>

**Expected behavior**
Will need to figure out how to process parent operations properly for these components.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: rc1

**Comment by kiersten-stokes** [comment]
As evidenced by the title change, this issue is only affecting an export to KFP Python DSL format. It's clear that a change to the jinja template for this format will be required, but will need to spend some more time researching exactly what that is. 

For now, it may be best to remove the option to export to DSL, since users will still have the option to export to YAML if needed.

**Comment by ptitzler** [comment]
Do you have the source code for this in a branch somewhere?
> Non-generic components are rendered as TaskSpec objects, and the DSL throws an error at the op.after function in processor_kfp.py:504, even though the same function succeeds when run during the 'submit' process.

**Comment by ptitzler** [comment]
See https://github.com/elyra-ai/elyra/issues/2301 for explanation
