### ISSUE TITLE
Pipeline Editor 'clear pipeline' button breaks UI

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1789]
**Describe the issue**
Watch the video!

![clear_pipeline](https://user-images.githubusercontent.com/13068832/122447350-7e6bd580-cf58-11eb-971e-b7124cd3fa7c.gif)

**To Reproduce**
1. Create any kind of pipeline using VPE
2. Clear pipeline
3. Expand properties panel
4. boom

**Comment by marthacryan** [comment]
Could you add any errors that show up on the console?

**Comment by kevin-bates** [comment]
Is see these in the console:
```
index.js:1 Uncaught TypeError: Cannot read property 'id' of null
    at Cn (index.js:1)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22779)
    at workLoopSync (react-dom.development.js:22707)
Cn @ index.js:1
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:20085 The above error occurred in the <Cn> component:

    at Cn (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:57139)
    at div
    at O (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:5492:19294)
    at Yn (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:61470)
    at div
    at O (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:5492:19294)
    at div
    at Ln (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:58012)
    at Rn (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:58833)
    at IntlProvider (http://localhost:8888/static/lab/vendors-node_modules_react-intl_lib_index_js.8a2162d88579cd78160c.js:4101:47)
    at div
    at O (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:5492:19294)
    at http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:63811
    at Ge (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:5492:16849)
    at V (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:25780)
    at div
    at Dropzone (http://localhost:8888/static/lab/vendors-node_modules_elyra_ui-components_lib_index_js.a89bfa3531954533a8a6.js:144552:11)
    at Ge (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:5492:16849)
    at exports.ThemeProvider (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor_dist_index_js.1109bc4b6fb7235b506a.js:61:73068)
    at PipelineWrapper (http://localhost:8888/static/lab/vendors-node_modules_elyra_pipeline-editor-extension_lib_index_js.3b16bb1651c9f911094c.js:278:28)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:11340 Uncaught TypeError: Cannot read property 'id' of null
    at Cn (index.js:1)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22779)
    at workLoopSync (react-dom.development.js:22707)
```
