### ISSUE TITLE
2.3/master VPE: Error making request HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1821]
**Describe the issue**
I've manually added components to the KFP catalog. Opening the VPE, the following error is displayed:

![image](https://user-images.githubusercontent.com/13068832/123135989-4b698c00-d407-11eb-8442-6dd510120d23.png)

and the log file contains these messages:

```
[I 2021-06-23 09:26:42.131 ServerApp] Retrieving pipeline components for kfp
[E 2021-06-23 09:26:42.352 ServerApp] Uncaught exception GET /elyra/pipeline/components/kfp?1624465602128 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/elyra/pipeline/components/kfp?1624465602128', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 108, in get
        components = await PipelineProcessorManager.instance().get_components(processor)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 87, in get_components
        res = await asyncio.get_event_loop().run_in_executor(None, processor.get_components)
      File "/opt/anaconda3/envs/master/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 172, in get_components
        components = self.component_registry.get_all_components(processor_type=self.type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 698, in get_all_components
        component_body = reader.get_component_body(component['path'][reader._type], parser._type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 649, in get_component_body
        component_body = urllib.request.urlopen(component_path)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
[E 2021-06-23 09:26:42.354 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
      "Authorization": "token f3f3dfeba6ed5e370cdcd37badb57dde6ebb6071c9c280b9",
      "X-Xsrftoken": "2|02e62ac5|f30dec00384d1e6f225ffcb6c2b83862|1623093581",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/untitled.pipeline",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8",
      "Cookie": "_xsrf=2|02e62ac5|f30dec00384d1e6f225ffcb6c2b83862|1623093581; username-localhost-8888=\"2|1:0|10:1624465599|23:username-localhost-8888|44:OTJiZjRmZDE0MzNkNGEwZWJjMmVjZDBhOWRhZmE3OTQ=|353300f6737c1a63d0085a6a7fe8138539bbb3fdf5d0eaf9a7222210c18c6d23\""
    }
[E 2021-06-23 09:26:42.354 ServerApp] 500 GET /elyra/pipeline/components/kfp?1624465602128 (::1) 223.13ms referer=http://localhost:8888/lab/tree/untitled.pipeline
[I 2021-06-23 09:27:16.242 ServerApp] Retrieving pipeline components for kfp
[E 2021-06-23 09:27:16.499 ServerApp] Uncaught exception GET /elyra/pipeline/components/kfp?1624465636223 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/elyra/pipeline/components/kfp?1624465636223', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 108, in get
        components = await PipelineProcessorManager.instance().get_components(processor)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 87, in get_components
        res = await asyncio.get_event_loop().run_in_executor(None, processor.get_components)
      File "/opt/anaconda3/envs/master/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 172, in get_components
        components = self.component_registry.get_all_components(processor_type=self.type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 698, in get_all_components
        component_body = reader.get_component_body(component['path'][reader._type], parser._type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 649, in get_component_body
        component_body = urllib.request.urlopen(component_path)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
[E 2021-06-23 09:27:16.500 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
      "Authorization": "token f3f3dfeba6ed5e370cdcd37badb57dde6ebb6071c9c280b9",
      "X-Xsrftoken": "2|02e62ac5|f30dec00384d1e6f225ffcb6c2b83862|1623093581",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/tree/untitled.pipeline",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8",
      "Cookie": "_xsrf=2|02e62ac5|f30dec00384d1e6f225ffcb6c2b83862|1623093581; username-localhost-8888=\"2|1:0|10:1624465602|23:username-localhost-8888|44:MWNlNmRiNDZjOWFlNGIwMDkwMzU5MzI0YTk3YTljOGQ=|b0685185e87f5a74aad1890b85056f9823e5ca6aa7f650511672630c9e9e2fbb\""
    }
[E 2021-06-23 09:27:16.500 ServerApp] 500 GET /elyra/pipeline/components/kfp?1624465636223 (::1) 258.65ms referer=http://localhost:8888/lab/tree/untitled.pipeline
[I 2021-06-23 09:27:27.119 ServerApp] Retrieving pipeline components for kfp
[E 2021-06-23 09:27:27.352 ServerApp] Uncaught exception GET /elyra/pipeline/components/kfp?1624465647115 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/elyra/pipeline/components/kfp?1624465647115', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 108, in get
        components = await PipelineProcessorManager.instance().get_components(processor)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 87, in get_components
        res = await asyncio.get_event_loop().run_in_executor(None, processor.get_components)
      File "/opt/anaconda3/envs/master/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 172, in get_components
        components = self.component_registry.get_all_components(processor_type=self.type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 698, in get_all_components
        component_body = reader.get_component_body(component['path'][reader._type], parser._type)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/registry.py", line 649, in get_component_body
        component_body = urllib.request.urlopen(component_path)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/opt/anaconda3/envs/master/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by ptitzler** [comment]
Expected behavior is that the URL that triggered the 404 is logged.
