### ISSUE TITLE
VPE becomes almost unusable if an invalid component specification location is provided

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1869]
**Describe the issue**
A clear and concise description of what the issue is.

- When the VPE detects that one or more component specifications cannot be accessed, the pipeline editor becomes fairly unusable because an error is raised over and over again:

![go_away](https://user-images.githubusercontent.com/13068832/124672931-c5206180-de6c-11eb-99f6-a39f9daf5f0e.gif)

 - The JupyterLab log file fills up quickly with entires like the one shown below because the editor continuously pulls the component registry

```
[E 2021-07-06 15:11:17.635 ServerApp] Uncaught exception GET /elyra/pipeline/components/kfp?1625609477576 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/elyra/pipeline/components/kfp?1625609477576', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 112, in get
        components: List[Component] = await PipelineProcessorManager.instance().get_components(processor)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 90, in get_components
        res = await asyncio.get_event_loop().run_in_executor(None, processor.get_components)
      File "/opt/anaconda3/envs/master/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 189, in get_components
        components.extend(self._component_registry.get_all_components())
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component_registry.py", line 191, in get_all_components
        self._update_cache()
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component_registry.py", line 203, in _update_cache
        self._cache = super().get_all_components()
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component_registry.py", line 71, in get_all_components
        component = self._parser.parse(component_entry)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component_parser_kfp.py", line 34, in parse
        component_yaml = self._read_component_yaml(registry_entry)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component_parser_kfp.py", line 137, in _read_component_yaml
        reader.read_component_definition(registry_entry.id, registry_entry.location)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/component.py", line 274, in read_component_definition
        raise FileNotFoundError (f'Invalid location for component: {component_id} -> {location} (HTTP code {res.status_code})')  # noqa: E211 E501
    FileNotFoundError: Invalid location for component: download-file -> https://raw.githubusercontent.com/ptitzler/kfp-component-tests/optional/download-file/component.yaml (HTTP code 404)
```

**To Reproduce**
1. Add a  KF component of type URL to the registry
2. Start Elyra
3. Invalidate the component URL (e.g. by removing the `component.yaml` from the location where it is stored or cutting network connectivity)

**Expected behavior**

- Display warning _once_ when the editor starts up, indicating that component(s) could not be loaded.
- Disable components in palette that cannot be used.

**Comment by lresende** [comment]
Components from the catalog that are not valid should just be logged and ignored...
