### ISSUE TITLE
Pipeline pre-processing fails for pipelines with custom components

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#1886]
**Describe the issue**

GUI message:

```
Error pre-processing pipeline untitled9 for engine Argo at /var/folders/h8/l3qh8v192rv_vvggc6wyphzc0000gn/T/tmp5r2us_zu/untitled9.tar.gz
```

Log file:

```
[I 2021-07-08 14:39:00.694 ServerApp] kfp 'untitled9' - submitting pipeline 
[I 2021-07-08 14:39:00.701 ServerApp] kfp 'untitled9' - processing pipeline dependencies to: http://cloning1.fyre.ibm.com:31467 bucket: ptitzler-test folder: untitled9-0708143857 
[E 2021-07-08 14:39:00.762 ServerApp] There was an error while constructing component Download File.
[E 2021-07-08 14:39:00.763 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1625780337186 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1625780337186', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 534, in _cc_pipeline
        notebook_ops[operation.id] = factory_function(**operation.component_params)
    TypeError: Download File() got an unexpected keyword argument 'label'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 188, in process
        kfp_argo_compiler.Compiler().compile(pipeline_function, pipeline_path)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 975, in compile
        package_path=package_path)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 1029, in _create_and_write_workflow
        pipeline_conf)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 861, in _create_workflow
        pipeline_func(*args_list, **kwargs_dict)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 184, in <lambda>
        cos_directory=cos_directory)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 538, in _cc_pipeline
        raise RuntimeError(f"There was an error while constructing component {operation.name}.")
    RuntimeError: There was an error while constructing component Download File.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 93, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 111, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/anaconda3/envs/master/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/master/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 193, in process
        format(pipeline_name, engine, pipeline_path), str(ex)) from ex
    RuntimeError: ('Error pre-processing pipeline untitled9 for engine Argo at /var/folders/h8/l3qh8v192rv_vvggc6wyphzc0000gn/T/tmp5r2us_zu/untitled9.tar.gz', 'There was an error while constructing component Download File.')
```

**To Reproduce**
1. Create KFP pipeline
2. Add and configure custom component.
3. Try to run the pipeline.

**Comment by akchinSTC** [comment]
getting an error creating a new pipeline, standby
