### ISSUE TITLE
Can't run generic pipeline on KFP server

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#2006]
**Describe the issue**
Can't run generic pipeline on KFP server

**To Reproduce**
1. Clone https://github.com/lresende/elyra-sample
2. Execute https://github.com/lresende/elyra-sample/blob/master/producer-consumer/pipelines/producer-consumer.pipeline
3. Error when trying to run the first node

```
Requirement already satisfied: packaging in /opt/conda/lib/python3.8/site-packages (20.4)
Requirement already satisfied: six in /opt/conda/lib/python3.8/site-packages (from packaging) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.8/site-packages (from packaging) (2.4.7)
[D 13:36:32.439] Parsing Arguments.....
[I 13:36:32.441] 'producer-consumer-0803093611':'setup' - starting operation 
[I 13:36:32.441] 'producer-consumer-0803093611':'setup' - Installing packages 
Traceback (most recent call last):
  File "bootstrapper.py", line 634, in <module>
    main()
  File "bootstrapper.py", line 617, in main
    OpUtil.package_install(user_volume_path=input_params.get('user-volume-path'))
  File "bootstrapper.py", line 505, in package_install
    elyra_packages = cls.package_list_to_dict("requirements-elyra.txt")
  File "bootstrapper.py", line 553, in package_list_to_dict
    package_name, package_version = line.strip('\n').split(sep="==")

ValueError: not enough values to unpack (expected 2, got 1)
```

![image](https://user-images.githubusercontent.com/382917/128025433-585a2727-92e4-4a09-b99a-8831d93f76dd.png)

Environment:
Tried with the latest master and RC1 and both are giving me the same results.

**Comment by lresende** [comment]
User error resolved after unsetting the debug env variables:
```
#export ELYRA_GITHUB_ORG=lresende
#export ELYRA_GITHUB_BRANCH=dev-kfp
```
