### ISSUE TITLE
airflow/email_operator triggers "malformed node or string" error during compilation 

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2020]
**Describe the issue**
A clear and concise description of what the issue is.

![image](https://user-images.githubusercontent.com/13068832/128561357-80c47601-8d20-42a7-9a32-e8b1decbce28.png)

**To Reproduce**
1. Install Elyra 3.0
2. Launch JupyterLab
3. Create AA pipeline
4. Add and configure email operator
4. Try to run the pipeline. See error

**Log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
[E 2021-08-06 12:16:23.700 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1628277383647 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1628277383647', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/elyra/pipeline/handlers.py", line 119, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/elyra/pipeline/processor.py", line 119, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/elyra/pipeline/processor_airflow.py", line 81, in process
        pipeline_filepath = self.create_pipeline_file(pipeline=pipeline,
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/elyra/pipeline/processor_airflow.py", line 318, in create_pipeline_file
        target_ops = self._cc_pipeline(pipeline, pipeline_name)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/site-packages/elyra/pipeline/processor_airflow.py", line 261, in _cc_pipeline
        operation.component_params[component_property.ref] = ast.literal_eval(op_property)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/ast.py", line 99, in literal_eval
        return _convert(node_or_string)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/ast.py", line 98, in _convert
        return _convert_signed_num(node)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/ast.py", line 75, in _convert_signed_num
        return _convert_num(node)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/ast.py", line 66, in _convert_num
        _raise_malformed_node(node)
      File "/opt/anaconda3/envs/ga_30/lib/python3.8/ast.py", line 63, in _raise_malformed_node
        raise ValueError(f'malformed node or string: {node!r}')
    ValueError: malformed node or string: <_ast.BinOp object at 0x7f865b947fd0>
</pre>
</details>

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0
 - Installation source: PyPI

**Comment by kiersten-stokes** [comment]
This is something that @akchinSTC and I were just discussing last week. The issue is related to how we're assigning and evaluating types. I'll give an example for the `to` parameter for this email operator.

The type of `to`, as given in the spec, is `list or string (comma or semicolon delimited)`. Our parsing logic then evaluates this as the standardized type `list`. Then, during processing, since this parameter's type is `list`, the value given for this parameter in the pipeline JSON is run through `ast.literal_eval()` in order to render it properly in the Airflow DAG.

So, it's another one of those questions in determining how to standardize parsing and pipeline processing. One potential solution might be to wrap the `literal_eval` in a try/except block, rendering the parameter as a string as a backup. We could also edit the operator file itself to be a bit more specific about what to enter in that field. This is definitely one of those things that we'll want to discuss further.

**Comment by kevin-bates** [comment]
Agreed.  I think there are a few more steps we can take in preparing for the eval call.  In some cases, there's no need for an eval, but only the appropriate form of `split()` (i.e., splitting on either comma or semi-colon) or appropriate initialization (when there's a single string with no brackets or separators), etc..  This area of the code could also use some debug logging as well.

I'd prefer we avoid altering the component definition itself and just make "type-processing" more robust.
