### ISSUE TITLE
elyra-pipeline CLI doesn't handle mismatched runtime values for empty pipelines

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2044]
**Describe the issue**

Follow up to  https://github.com/elyra-ai/elyra/issues/2037:

```
$ elyra-pipeline submit empty-airflow.pipeline --runtime-config my_kubeflow_test_instance

────────────────────────────────────────────────────────────────
 Elyra Pipeline Submission
────────────────────────────────────────────────────────────────

Traceback (most recent call last):
  File "/opt/anaconda3/envs/upstream/bin/elyra-pipeline", line 8, in <module>
    sys.exit(pipeline())
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/cli/pipeline_app.py", line 263, in submit
    _preprocess_pipeline(pipeline_path, runtime=runtime, runtime_config=runtime_config)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/cli/pipeline_app.py", line 141, in _preprocess_pipeline
    runtime_description = primary_pipeline['app_data']['properties']['runtime']
KeyError: 'properties'

```

**To Reproduce**

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
Paste the log output here.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0/master
 - Installation source: from source

**Comment by ptitzler** [comment]
Might be resolved by https://github.com/elyra-ai/elyra/pull/2041?
