### ISSUE TITLE
Pipeline submission fails with 'kfp_server_api.exceptions.ApiTypeError: Got an unexpected keyword argument 'description' to method upload_pipeline_version'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2085]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
1. Create a KFP RTC
2. Create a notebook
2. Create a pipeline
3. Add notebook to pipeline
3. Try to run pipeline (using VPE or CLI)

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
[E 2021-08-31 09:50:19.093 ServerApp] Uncaught exception POST /elyra/pipeline/schedule?1630396214589 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/schedule?1630396214589', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 119, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 121, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 230, in process
        pipeline_id=pipeline_id)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/kfp/_client.py", line 1143, in upload_pipeline_version
        description=description,
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 209, in upload_pipeline_version
        return self.upload_pipeline_version_with_http_info(uploadfile, **kwargs)  # noqa: E501
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 265, in upload_pipeline_version_with_http_info
        " to method upload_pipeline_version" % key
    kfp_server_api.exceptions.ApiTypeError: Got an unexpected keyword argument 'description' to method upload_pipeline_version
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.1/master
 
```
$ pip list | grep kfp
kfp                               1.7.2
kfp-pipeline-spec                 0.1.9
kfp-server-api                    1.7.0
```

**Comment by ptitzler** [comment]
Surfaces in kfp==`1.7.2`. Need to downgrade to `1.7.1` until https://github.com/kubeflow/pipelines/pull/6468 is available in a published released.
