### ISSUE TITLE
The new 'Airflow Pipeline Editor' feature is not working properly. DAGs created with this function will be recognized as errors by 'Airflow'.

### ISSUE THREAD

**Issue by nanaones** [elyra-ai/elyra#2124]
**Describe the issue**
Airflow Pipeline Generator generates malformed DAG files.

**To Reproduce**
1. Go to 'Airflow pipeline Editor on Launcher'
2. Drag 'BashOperator on template'
3. Fill bash_command on Node properties 'echo hello-world'
4. Click Run pipeline on Apache Airflow
5. Fill 'Pipeline Name' to 'hello-world'

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Broken DAG: [/opt/airflow/dags/repo/hello-world-0909015623.py] Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 414, in __init__
    "arguments were:\n**kwargs: {k}".format(c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: BashOperator). Invalid arguments were:
**kwargs: {'namespace': 'airflow', 'xcom_push': False, 'inputs': [], 'outputs': [], 'secrets': [Secret(env, AWS_ACCESS_KEY_ID, elyra, AWS_ACCESS_KEY_ID), Secret(env, AWS_SECRET_ACCESS_KEY, elyra, AWS_SECRET_ACCESS_KEY)], 'in_cluster': True, 'config_file': 'None'}</summary>

</details>

**Expected behavior**
The hello-world DAG performs the 'echo hello' behavior.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.0.1
 - Operating system: windows 10 
 - Installation source: Pip install 
 - Deployment type: EKS(Kubernetes v 1.21)

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Apache Airflow  Version 2.0.2 
 
The same goes for EmailOperators.
I checked because the generated dags passing arguments are based on k8soperator.

**Comment by ptitzler** [comment]
Unfortunately Airflow 2.x is not yet supported. https://elyra.readthedocs.io/en/stable/recipes/configure-airflow-as-a-runtime.html

**Comment by shalberd** [comment]
@lresende @ianonavy for Airflow 2.x package catalog connector / wheel file, it is not enough to just change the BaseOperator class. When the properties of airflow components are added, the parsing of the properties and its init fields needs to be changed, too, at https://github.com/kiersten-stokes/elyra/blob/main/elyra/pipeline/airflow/component_parser_airflow.py#L214

Why? Because the format changed (example bash operator) between

Airflow 1.10, for example

https://github.com/apache/airflow/blob/v1-10-stable/airflow/operators/bash_operator.py#L43
https://github.com/apache/airflow/blob/v1-10-stable/airflow/operators/bash_operator.py#L93

and Airflow current

https://github.com/apache/airflow/blob/main/airflow/operators/bash.py#L48
https://github.com/apache/airflow/blob/main/airflow/operators/bash.py#L138

I'll make sure to cover and test this in my PR
