### ISSUE TITLE
'elyra-pipeline validate' command fails for generic pipelines

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2147]
**Describe the issue**

```
$ elyra-pipeline validate generic.pipeline

────────────────────────────────────────────────────────────────
 Elyra Pipeline Validation
────────────────────────────────────────────────────────────────

Validating pipeline...
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ga_31/bin/elyra-pipeline", line 8, in <module>
    sys.exit(pipeline())
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/cli/pipeline_app.py", line 257, in validate
    _validate_pipeline_definition(pipeline_definition)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/cli/pipeline_app.py", line 178, in _validate_pipeline_definition
    PipelineValidationManager.instance().validate(pipeline=pipeline_definition))
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/pipeline/validation.py", line 152, in validate
    response=response)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/pipeline/validation.py", line 255, in _validate_node_properties
    component_list = await PipelineProcessorManager.instance().get_components(pipeline_runtime)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 98, in get_components
    processor = self._get_processor_for_runtime(processor_type)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 91, in _get_processor_for_runtime
    processor = self._registry.get_processor(processor_type)
  File "/opt/anaconda3/envs/ga_31/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 76, in get_processor
    raise RuntimeError('Could not find pipeline processor for [{}]'.format(processor_type))
RuntimeError: Could not find pipeline processor for [None]
```
**To Reproduce**
1. Create a notebook
1. Create a generic pipeline
2. Add notebook to pipeline
3. Save pipeline
2. Run `elyra-pipeline validate ...`

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.1+

**Comment by lresende** [comment]
How did you create the pipeline? Is it missing the runtime field information?

**Comment by ptitzler** [comment]
> How did you create the pipeline? Is it missing the runtime field information?

See updated instructions - it's a plain vanilla pipeline. [recreate.tar.gz](https://github.com/elyra-ai/elyra/files/7171680/recreate.tar.gz)
