### ISSUE TITLE
elyra-metadata install component-registries doesn't seem to work for URL entries?

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2154]
**Describe the issue**

 Not sure why it is not, but the following _should_ be a valid invocation 

```
$ elyra-metadata install component-registries --display_name="data load components" --description="Load data from external data sources" --runtime=kfp --location_type=URL --paths="https://raw.githubusercontent.com/elyra-ai/elyra/master/etc/config/components/kfp/run_notebook_using_papermill.yaml"
```

but fails with

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/upstream/bin/elyra-metadata", line 8, in <module>
    sys.exit(MetadataApp.main())
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 330, in main
    elyra_metadata.start()
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 342, in start
    return subinstance.start()
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 275, in start
    return subinstance.start()
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 197, in start
    super().start()  # process options
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 51, in start
    self.process_cli_options(self.options)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 300, in process_cli_options
    self.process_cli_option(option)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 270, in process_cli_option
    cli_option.set_value(self.argv_mappings.get(option))
  File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 50, in set_value
    self.value = ast.literal_eval(value)
  File "/opt/anaconda3/envs/upstream/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/opt/anaconda3/envs/upstream/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    https://raw.githubusercontent.com/elyra-ai/elyra/master/etc/config/components/kfp/run_notebook_using_papermill.yaml
```

The problematic parameter is the `path` parameter value because the error is not triggered if it is omitted. Since the provided is a valid URL, I'm not sure what I'm missing. 

**To Reproduce**
See above

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.1.1

**Comment by ptitzler** [comment]
https://github.com/elyra-ai/elyra/pull/2104 attempts to mitigate the problem somewhat but is of no help if the user does not read the documentation. In general it would be useful if the help would provide examples for array-type inputs, e.g.

```
$ elyra-metadata install  component-registries
'--display_name' is a required parameter.

Install a metadata instance into namespace 'component-registries'.

Options
-------

...
--paths=<array>
	A list of absolute paths to individual component specification files or to repositories containing multiple component files (e.g., a directory in the file system). Example: `['/path/to/file','/path/to/another/file']`

```

**Comment by kevin-bates** [comment]
We used to provide rich meta-property details in the help, but we felt it was too much and it was removed. See https://github.com/elyra-ai/elyra/pull/841.  But that was more about the schema content itself, and I suppose we could trim things down, like only convey min/max values, etc.  I do agree that the more complicated types, like `array` or `object` (which isn't supported by the tooling today), probably deserve a callout.  I do believe, however, that, for `array` we should try to include the meta-information regarding the expected entries (strings, integers, booleans, etc.).
