### ISSUE TITLE
Error running pipeline with custom components

### ISSUE THREAD

**Issue by VMeghanaReddy** [elyra-ai/elyra#2223]
Created a pipeline with "_run notebook using papermill_" kfp custom component. Notebook parameter of the component is updated with notebook _https://github.com/elyra-ai/examples/blob/master/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/a-notebook.ipynb._

Below is error message while running the pipeline.

**Error Message** : 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 207, in process
    kfp_argo_compiler.Compiler().compile(pipeline_function,
  File "/opt/conda/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1179, in compile
    self._create_and_write_workflow(
  File "/opt/conda/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1231, in _create_and_write_workflow
    workflow = self._create_workflow(pipeline_func, pipeline_name,
  File "/opt/conda/lib/python3.8/site-packages/kfp/compiler/compiler.py", line 1009, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 194, in <lambda>
    pipeline_function = lambda: self._cc_pipeline(pipeline,  # nopep8 E731
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 534, in _cc_pipeline
    self.log.debug(f"Processing component parameter '{component_property.name}' "
AttributeError: 'ComponentParameter' object has no attribute 'type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/handlers.py", line 118, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor.py", line 113, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor_kfp.py", line 213, in process
    raise RuntimeError('Error pre-processing pipeline {} for engine {} at {}'.
RuntimeError: ('Error pre-processing pipeline untitled2 for engine Argo at /tmp/tmpi3sv_ihj/untitled2.tar.gz', "'ComponentParameter' object has no attribute 'type'")

Thankyou.

**Comment by ptitzler** [comment]
@VMeghanaReddy did you run the [example pipeline](https://github.com/elyra-ai/examples/blob/master/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/run_notebook_using_papermill.pipeline) or did you create your own?

**Comment by VMeghanaReddy** [comment]
@ptitzler, I am using the latest version of elyra. 
When trying to open [example pipeline](https://github.com/elyra-ai/examples/blob/master/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/run_notebook_using_papermill.pipeline) it says "_error loading pipeline_". So I build a pipeline with one custom component "_Run notebook using papermill_" and passed [notebook](https://github.com/elyra-ai/examples/blob/master/pipelines/kubeflow_pipelines_component_examples/run_notebook_component/a-notebook.ipynb) in parameters.

**Comment by VMeghanaReddy** [comment]
Installed new version 3.2. I can open the pipeline. There is an error in Kubeflow authentication while running the pipeline.

_RuntimeError: Failed to create istio auth session for Kubeflow endpoint: 'http://ml-pipeline.kubeflow.svc.cluster.local:8888' - Check Kubeflow Pipelines runtime configuration: 'kubeflow'_

Using the same Kubeflow credentials it is working in an older version of elyra. The issue is only in the new version.

**Comment by thesuperzapper** [comment]
@VMeghanaReddy are you using LDAP auth by any chance?

Because I thought we were waiting for https://github.com/elyra-ai/elyra/pull/2212 to be merged before releasing `3.2.0`.

**Comment by ptitzler** [comment]
Hi @VMeghanaReddy,

version 3.3 was just released which improves support for KFP authentication. Can you please try again and re-open the issue if the problem still exists? Thank you!
