### ISSUE TITLE
Conda env export fails due to incorrect PyPI spec parsing 

### ISSUE THREAD

**Issue by rxm7706** [elyra-ai/elyra#2341]
**Describe the issue**

conda export will fail if elyra >3.3 is installed via pip in a conda enviornment
Known Conda issue when setup.py cannot be parsed - in this case the cause seems to be version spec for kfp
https://github.com/conda/conda/issues/9624
Appears it can be solved by adding a comma for kfp specs between 1.6.3 and <2.0
https://github.com/elyra-ai/elyra/blob/master/setup.py#L104
        'kfp>=1.6.3<2.0,!=1.7.2',
        to
        'kfp>=1.6.3,<2.0,!=1.7.2',

**To Reproduce**
1. conda create -n elyra python=3.8.12 jupyterlab
2. conda activate elyra
3. pip3 install --upgrade --upgrade-strategy only-if-needed --use-deprecated legacy-resolver --no-cache-dir elyra-pipeline-editor-extension==3.3.0rc2
4. conda export -n elyra
5. Error will be KeyError: '!=1.7.2,>=1.6.3<2.0'

This can be manually fixed by editing the METADATA of elyra server in site packages vi <CONDA_PREFIX>/envs/elyra/lib/python3.8/site-packages/elyra_server-3.3.0rc2.dist-info/METADATA
Requires-Dist: kfp (!=1.7.2,>=1.6.3<2.0) to Requires-Dist: kfp (!=1.7.2,>=1.6.3,<2.0)

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Log Output</summary>
<pre>
/Projects$ conda export -n elyra
Traceback (most recent call last):
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '!=1.7.2,>=1.6.3<2.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '>=1.6.3<2.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '1.6.3<2.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<CONDA_PREFIX>/bin/conda-export", line 10, in <module>
    sys.exit(main())
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda_export.py", line 86, in main
    env_all = from_environment(args.name, prefix, no_builds=True)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda_env/env.py", line 109, in from_environment
    precs = tuple(PrefixGraph(pd.iter_records()).graph)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/prefix_graph.py", line 39, in __init__
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/prefix_graph.py", line 39, in <genexpr>
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/match_spec.py", line 55, in __call__
    return super(MatchSpecType, cls).__call__(**parsed)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/match_spec.py", line 177, in __init__
    self._match_components = self._build_components(**kwargs)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/match_spec.py", line 403, in _build_components
    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/match_spec.py", line 403, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/match_spec.py", line 417, in _make_component
    matcher = _implementors[field_name](value)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 497, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 508, in get_matcher
    tup = tuple(VersionSpec(s) for s in vspec_tree[1:])
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 508, in <genexpr>
    tup = tuple(VersionSpec(s) for s in vspec_tree[1:])
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 497, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 546, in get_matcher
    self.matcher_vo = VersionOrder(vo_str)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "<CONDA_PREFIX>/lib/python3.8/site-packages/conda/models/version.py", line 172, in __init__
    raise InvalidVersionSpec(vstr, "invalid character(s)")
conda.exceptions.InvalidVersionSpec: Invalid version '1.6.3<2.0': invalid character(s)
</pre>
</details>

**Expected behavior**
$ conda export -n elyra
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - python=3.8.12
  - pip:
    - elyra-pipeline-editor-extension
    - flake8
    - pydocstyle
    - pylint
    - rope
    - yapf
name: elyra

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [3.3.0rc2]
 - Installation source: [conda environment with pip to install elyra]
 - Deployment type: [local installation]
 - Operating system: [linux - WSL on windows]

**Comment by Hanuphant** [comment]
How was this issue resolved?

**Comment by rxm7706** [comment]
> How was this issue resolved?

https://github.com/elyra-ai/elyra/pull/2342/commits/5bf7d09e89649bc1d247aea707c2d665d1775615

as described in the issue detail, by fixing the setup.py - just adding a comma between versions

`'kfp>=1.6.3<2.0,!=1.7.2',` 
 `'kfp>=1.6.3,<2.0,!=1.7.2',`
