### ISSUE TITLE
Pipeline processing fails for installation validation pipeline

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2461]
**Describe the issue**

Processing for the setup validation pipeline in https://github.com/elyra-ai/examples/tree/master/pipelines/setup_validation fails:

![image](https://user-images.githubusercontent.com/13068832/153079041-3882bdaa-0c81-4504-a677-7f3d2b0e7685.png)

This used to work in earlier releases. 

**To Reproduce**
1. Clone the examples repository
2. Open the pipeline file in the `pipelines/setup_validation` directory
3. Try to run the pipeline on KFP

**Screenshots or log output**
If applicable, add screenshots or log output to help explain your problem.
<details><summary>Error message</summary>
<pre>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 120, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 134, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/anaconda3/envs/rct/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/elyra/pipeline/airflow/processor_airflow.py", line 125, in process
    pipeline_name=pipeline_name)
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/elyra/pipeline/airflow/processor_airflow.py", line 444, in create_pipeline_file
    output_to_file = black.format_str(autopep_output, mode=black.FileMode())
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/black/__init__.py", line 1077, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/opt/anaconda3/envs/rct/lib/python3.7/site-packages/black/parsing.py", line 132, in lib2to3_parse
    raise exc from None
black.parsing.InvalidInput: Cannot parse: 15:16:     description='Use this pipeline to test your JupyterLab, Kubeflow Pipelines, or Apache Airflow environment setup.
</pre>
</details>

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.6/rc0

**Comment by ptitzler** [comment]
It appears that the issue is with the pipeline description:
 - create a new Airflow pipeline
 - add the following description
```
Use this pipeline to test your JupyterLab, Kubeflow Pipelines, or Apache Airflow environment setup.

If your setup is correct, this pipeline should run as is:
 - To test JupyterLab, click the "run" button and choose "Local Runtime" as Runtime Platform.
 - To test Kubeflow Pipelines, create a Kubeflow Pipelines runtime configuration, then click the "run" button and select "Kubeflow Pipelines" as Runtime Platform.
 - To test Apache Airflow, create an Apache Airflow runtime configuration, then click the "run" button and select "Apache Airflow" as Runtime Platform.
```
 - add a dummy node (no comments)
 - export the pipeline

**Comment by ptitzler** [comment]
There are two issues that need to be addressed:
 - use multi-line strings in the [Jinja template](https://github.com/elyra-ai/elyra/blob/master/elyra/templates/airflow/airflow_template.jinja2)  whenever user-provided input is dumped (e.g. 
   ```
    description="""{{ pipeline_description }}""",
   ```
 - Escape `"""` in the string that is to be rendered to avoid breaking the multi-line string designation

**Comment by kiersten-stokes** [comment]
> - use multi-line strings in the [Jinja template](https://github.com/elyra-ai/elyra/blob/master/elyra/templates/airflow/airflow_template.jinja2) whenever user-provided input is dumped (e.g.
 description="""{{ pipeline_description }}""",
> - Escape """ in the string that is to be rendered to avoid breaking the multi-line string designation

We're having a similar issue with descriptions in the component properties template, so I was just looking into this. I believe an alternative solution, which might save us the trouble of the latter bullet point, is to use the following in the template:

```
description={{ pipeline_description|tojson|safe }}
```

This should also take care of additional situations with un-escapted characters sneaking into descriptions. Still have to test this to make sure it doesn't cause any unexpected behavior, however
