### ISSUE TITLE
Notebook pipelines are failing on KFP and Airflow

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2491]
**Describe the issue**

[Confirmed. Not pipeline specific]

```
load_data.ipynb
[I 18:07:22.295] 'analyze_NOAA_weather_data-0218100646':'load_data' - dependencies processed (0.067 secs)
[I 18:07:22.296] 'analyze_NOAA_weather_data-0218100646':'load_data' - executing notebook using 'papermill load_data.ipynb load_data-output.ipynb' 
[D 18:07:22.994] Found kernel python3 in /usr/local/share/jupyter/kernels
[I 18:07:23.115] Input Notebook:  load_data.ipynb
[I 18:07:23.115] Output Notebook: load_data-output.ipynb
[E 18:07:23.121] Unexpected error: <class 'KeyError'>
[I 18:07:23.360] 'analyze_NOAA_weather_data-0218100646':'load_data' - converting from load_data-output.ipynb to load_data.html 
Traceback (most recent call last):
  File "bootstrapper.py", line 373, in execute
    papermill.execute_notebook(notebook, notebook_output, kernel_name=kernel_name)
  File "/usr/local/lib/python3.8/site-packages/papermill/execute.py", line 90, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/usr/local/lib/python3.8/site-packages/papermill/iorw.py", line 461, in load_notebook_node
    nb_upgraded = nbformat.v4.upgrade(nb)
  File "/usr/local/lib/python3.8/site-packages/nbformat/v4/convert.py", line 39, in upgrade
    _warn_if_invalid(nb, from_version)
  File "/usr/local/lib/python3.8/site-packages/nbformat/v4/convert.py", line 21, in _warn_if_invalid
    validate(nb, version=version)
  File "/usr/local/lib/python3.8/site-packages/nbformat/validator.py", line 274, in validate
    for error in iter_validate(nbdict, ref=ref, version=version,
  File "/usr/local/lib/python3.8/site-packages/nbformat/validator.py", line 298, in iter_validate
    validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
  File "/usr/local/lib/python3.8/site-packages/nbformat/validator.py", line 69, in get_validator
    schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
  File "/usr/local/lib/python3.8/site-packages/nbformat/validator.py", line 103, in _get_schema_json
    schema_path = os.path.join(os.path.dirname(v.__file__), v.nbformat_schema[(None, None)])
KeyError: (None, None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nbformat/__init__.py", line 138, in read
    buf = fp.read()
AttributeError: 'str' object has no attribute 'read'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bootstrapper.py", line 653, in <module>
    main()
  File "bootstrapper.py", line 643, in main
    file_op.execute()
  File "bootstrapper.py", line 385, in execute
    NotebookFileOp.convert_notebook_to_html(notebook_output, notebook_html)
  File "bootstrapper.py", line 403, in convert_notebook_to_html
    nb = nbformat.read(notebook_file, as_version=4)
  File "/usr/local/lib/python3.8/site-packages/nbformat/__init__.py", line 140, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'load_data-output.ipynb'
```

**To Reproduce**
1. Clone examples repository
2. Open and run NOAA example pipeline on KFP/Airflow (Or create a pipeline that runs a notebook, which produces output)

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7/master

**Comment by ptitzler** [comment]
Confirmed - old/working:
```
papermill==2.1.2
nbformat==5.0.7
```

using this test:
```
import papermill
papermill.execute_notebook('debug-hello.ipynb', 'debug-hello-out.ipynb', kernel_name='python3')
```

Confirmed - current/broken:
```
papermill==2.3.4 
nbformat==5.0.7 -->  required is 5.1.3
```
