### ISSUE TITLE
elyra-metadata create|install|update fails unexpectedly if required parameter is missing

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2640]
**Describe the issue**

For example, run `elyra-metadata create runtimes --file` or `elyra-metadata create runtimes --json` without specifying an argument. There's a high probability that this problem applies to all commands that accept an input argument in the form of `--key=<value>`

```
 $ elyra-metadata create runtimes --file             
Traceback (most recent call last):
  File "/opt/anaconda3/envs/emissary/bin/elyra-metadata", line 8, in <module>
    sys.exit(MetadataApp.main())
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 900, in main
    elyra_metadata.start()
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 919, in start
    return subinstance.start()
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 795, in start
    subinstance = subcommand[0](argv=self.argv, schemaspace_schemas=self.schemaspace_schemas)
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 230, in __init__
    bulk_metadata = self._process_json_based_options()
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app.py", line 315, in _process_json_based_options
    self.process_cli_option(self.file_option, check_help=True)
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 510, in process_cli_option
    cli_option.set_value(self.argv_mappings.get(option))
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 413, in set_value
    super().set_value(value)
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 67, in set_value
    self.value = self._get_object_value(value)
  File "/opt/anaconda3/envs/emissary/lib/python3.7/site-packages/elyra/metadata/metadata_app_utils.py", line 102, in _get_object_value
    if os.path.isfile(value):
  File "/opt/anaconda3/envs/emissary/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Expected behavior**
- No exception
- Error message states that a parameter value is required

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.7

**Comment by ptitzler** [comment]
For context, the `elyra-pipeline` CLI requires parameters to be specified as `--key <value>`. Due to the syntax difference users might accidentally omit  `=` when running `elyra-metadata`: 
```
$ elyra-metadata create runtimes --file myfile.json
 *boom*
```
