### ISSUE TITLE
Cannot execute Kubeflow Pipeline in secured OpenShift environment

### ISSUE THREAD

**Issue by lehrig** [elyra-ai/elyra#2724]
**Describe the issue**
After having secured our Kubeflow cluster with OpenShift OAuth, Elyra seems to have issues executing a pipeline in this cluster (in-cluster, from within a Kubeflow notebook server). Executing fails with this issue (see detailed logs further below):
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)
```

I'm using ```KUBERNETES_SERVICE_ACCOUNT_TOKEN``` and am not sure whether this works correctly given our OpenShift OAuth setup. Also, note that using the Kubeflow Pipelines SDK, everything works as expected:

```
client = kfp.Client()
...
client.create_run_from_pipeline_func(
    my_pipeline,
    namespace='user-example-com'
)
```
...successfully creates a pipeline run.

**To Reproduce**
1. Setup OAuth with Kubeflow in OpenShift
2. Start a new notebook server featuring Elyra
3. Try to run a pipeline against the Kubeflow cluster

**Screenshots or log output**
![Bildschirmfoto 2022-05-12 um 13 45 41](https://user-images.githubusercontent.com/9555494/168068474-1deaf7e7-0b2d-44e7-b82d-828219fea5d9.png)

<details><summary>Log Output</summary>
<pre>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 158, in process
    client.list_experiments(namespace=user_namespace, page_size=1)
  File "/opt/conda/lib/python3.8/site-packages/kfp/_client.py", line 533, in list_experiments
    response = self._experiment_api.list_experiment(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/experiment_service_api.py", line 567, in list_experiment
    return self.list_experiment_with_http_info(**kwargs)  # noqa: E501
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api/experiment_service_api.py", line 668, in list_experiment_with_http_info
    return self.api_client.call_api(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/opt/conda/lib/python3.8/site-packages/kfp_server_api/rest.py", line 208, in request
    r = self.pool_manager.request(method, url,
  File "/opt/conda/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kubeflow.apps.edb-p1306.cecc.ihost.com', port=443): Max retries exceeded with url: /pipeline/apis/v1beta1/experiments?page_token=&page_size=1&sort_by=&resource_reference_key.type=NAMESPACE&resource_reference_key.id=user-example-com (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/handlers.py", line 133, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/processor.py", line 143, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/conda/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/opt/conda/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 165, in process
    raise RuntimeError(
RuntimeError: Failed to `kfp.Client().list_experiments()` against: 'https://kubeflow.apps.edb-p1306.cecc.ihost.com/pipeline' - Check Kubeflow Pipelines runtime configuration: 'dev_runtime_-_kubeflow_pipelines' - [TIP: ensure namespace 'user-example-com' is correct]
</pre>
</details>

**Expected behavior**
Pipeline should execute successfully.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.8.0
 - Operating system: linux (RHEL 8.4 on ppc64le; SELinux enabled)
 - Installation source: custom container image (https://github.com/lehrig/kubeflow-ppc64le-notebook-images -> quay.io/ibm/kubeflow-notebook-image-ppc64le:elyra3.8.0-py3.8-tensorflow-cpu2.7.0)
 - Deployment type: Kubeflow (v1.5.0) Notebook Server on OpenShift v4.8

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines (v1.5.0, multi-user auth enabled using OpenShift OAuth)
 
**Runtime configuration settings**
![Bildschirmfoto 2022-05-12 um 13 49 34](https://user-images.githubusercontent.com/9555494/168068447-a3935ca6-5229-4c23-8587-91f6de122f25.png)

**Comment by lehrig** [comment]
- this one also fails with the same error using the KFP client initialized via:
`client = kfp.Client(host="kubeflow.apps.edb-p1306.cecc.ihost.com")`

- this one works:
`client = kfp.Client(host="http://ml-pipeline.kubeflow.svc.cluster.local:8888/")`

-> together with https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#public-kubeflow-pipelines-api-endpoint-public-api-endpoint, I was also able to make it work with Elyra using the in-cluster host.

Great - thanks for your support!
