### ISSUE TITLE
Pipeline submission fails for Airflow due to parsing error

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#2866]
**Describe the issue**
While testing https://github.com/elyra-ai/elyra/pull/2865 I noticed that pipeline submission fails if a pipeline default value for runtime image is configured:

![image](https://user-images.githubusercontent.com/13068832/182306386-6a3cc8a9-befe-48ee-884b-15a0281134fc.png)

```
[E 2022-08-02 08:15:31.864 ServerApp] Uncaught exception POST /elyra/pipeline/export?1659420931689 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/elyra/pipeline/export?1659420931689', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 108, in post
        pipeline, pipeline_export_format, pipeline_export_path, pipeline_overwrite
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 156, in export
        None, processor.export, pipeline, pipeline_export_format, pipeline_export_path, overwrite
      File "/opt/anaconda3/envs/upstream/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/airflow/processor_airflow.py", line 218, in export
        pipeline_instance_id=pipeline_instance_id,
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/elyra/pipeline/airflow/processor_airflow.py", line 533, in create_pipeline_file
        output_to_file = black.format_str(autopep_output, mode=black.FileMode())
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/black/__init__.py", line 1077, in format_str
        src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
      File "/opt/anaconda3/envs/upstream/lib/python3.7/site-packages/black/parsing.py", line 132, in lib2to3_parse
        raise exc from None
    black.parsing.InvalidInput: Cannot parse: 52:39:     runtime_image=tensorflow/tensorflow: 2.8.0,
```

**To Reproduce**
1. Create an Airflow pipeline
2. Configure the 'runtime image' pipeline default 
3. Add a custom component/operator to the pipeline (e.g. bash) and configure it properly
4. Export pipeline

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.11/main

**Comment by kiersten-stokes** [comment]
I looked into it, and this is another issue with property propagation (😬). I'll add the fix to #2865
