### ISSUE TITLE
Public COS endpoint ignored

### ISSUE THREAD

**Issue by romeokienzler** [elyra-ai/elyra#2929]
**Describe the issue**
Public COS endpoint runtime configuration is ignored, Elyra still tries to upload assets via internal endpoint. This doesn't work in a scenario where Elyra runs outside the kubernetes cluster. 

**To Reproduce**
1. Install KFP Tekton in KIND
2. Configure http://minio-service.kubeflow:9000 as COS endpoint in Elyra
3. Port-Forward minio on host machine to minio svc such that localhost:9000 gets forwarded to minio svc

Submit pipeline

**Screenshots or log output**
[E 2022-09-16 09:33:21.743 ElyraApp] No components could be found in any catalog for platform type 'KUBEFLOW_PIPELINES'.
[I 2022-09-16 09:33:21.750 ElyraApp] kfp 'hello-generic-world' - Exporting pipeline as a .yaml file
[I 2022-09-16 09:33:21.750 ElyraApp] Compiling pipeline for Tekton engine
[I 2022-09-16 09:33:21.753 ElyraApp] kfp 'hello-generic-world' - processing pipeline dependencies for upload to 'http://minio-service.kubeflow:9000/' bucket 'test' folder 'hello-generic-world-0916093321'
[E 2022-09-16 09:33:27.771 ServerApp] Uncaught exception POST /elyra/pipeline/export?1663317201732 (::1)
  HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/elyra/pipeline/export?1663317201732', version='HTTP/1.1', remote_ip='::1')
  Traceback (most recent call last):
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12d5e2fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/processor.py", line 465, in _verify_cos_connectivity
    CosClient(runtime_configuration)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/util/cos.py", line 101, in __init__
    if not self.client.bucket_exists(self.bucket):
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/minio/api.py", line 652, in bucket_exists
    self._execute("HEAD", bucket_name)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/minio/api.py", line 394, in _execute
    region = self._get_region(bucket_name, None)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/minio/api.py", line 461, in _get_region
    response = self._url_open(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/minio/api.py", line 266, in _url_open
    response = self._http.urlopen(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
   [Previous line repeated 2 more times]
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-service.kubeflow', port=9000): Max retries exceeded with url: /test?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12d5e2fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/handlers.py", line 107, in post
    pipeline_exported_path = await PipelineProcessorManager.instance().export(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/processor.py", line 155, in export
    res = await asyncio.get_event_loop().run_in_executor(
   File "/usr/local/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 417, in export
    kfp_tekton_compiler.TektonCompiler().compile(pipeline_function, absolute_pipeline_export_path)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/kfp_tekton/compiler/compiler.py", line 1605, in compile
    super().compile(pipeline_func, package_path, type_check, pipeline_conf=pipeline_conf)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/kfp/compiler/compiler.py", line 1175, in compile
    self._create_and_write_workflow(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/kfp_tekton/compiler/compiler.py", line 1759, in _create_and_write_workflow
    pipeline_loop_crs, workflow = self.prepare_workflow(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/kfp_tekton/compiler/compiler.py", line 1670, in prepare_workflow
    workflow = self._create_workflow(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/kfp_tekton/compiler/compiler.py", line 1527, in _create_workflow
    pipeline_func(*args_list)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 412, in <lambda>
    pipeline_function = lambda: self._cc_pipeline(
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 492, in _cc_pipeline
    self._verify_cos_connectivity(runtime_configuration)
   File "/Users/boris/Library/Python/3.8/lib/python/site-packages/elyra/pipeline/processor.py", line 467, in _verify_cos_connectivity
    raise RuntimeError(
  RuntimeError: Error connecting to cloud storage: HTTPConnectionPool(host='minio-service.kubeflow', port=9000): Max retries exceeded with url: /test?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12d5e2fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). Update runtime configuration 'kfp local' and try again.
[E 2022-09-16 09:33:27.773 ServerApp] {
   "Host": "localhost:8888",
   "Accept": "*/*",
   "Referer": "http://localhost:8888/lab/tree/hello-generic-world.pipeline",
   "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
  }
[E 2022-09-16 09:33:27.773 ServerApp] 500 POST /elyra/pipeline/export?1663317201732 (::1) 6038.60ms referer=http://localhost:8888/lab/tree/hello-generic-world.pipeline

**Expected behavior**
Elyra should use the public endpoint to upload assets to COS 

**Pipeline runtime environment**
to be provided by boris
 
**Runtime configuration settings**
to be provided by boris

**Comment by ptitzler** [comment]
The purpose of the public endpoint is to provide the user with the ability to access the s3 ui. The pipeline editor always uses the 'internal' endpoint, where internal refers to a URL that can properly be resolved in the environment where Elyra is running. That means it can be an in-cluster URL or a public URL, if the minio service is exposed via istio.

**Comment by romeokienzler** [comment]
Since this works as designed the workaround for a local KIND test installation is:

1. Use a free dyndns provider like https://freedns.afraid.org/ and create an entry your_cos_name.some.ending pointing to the IP you see for minio when u run "k get svc -n kubeflow"
2. in your /etc/hosts on your laptop enter 127.0.0.1  your_cos_name.some.ending

that way inside the pod the svc IP is returned by the dyndns service, and on your elyra host machine 127.0.0.1 is returned
