### ISSUE TITLE
cos_directory_prefix is ignored in runtimes and the restricted PSS are violated

### ISSUE THREAD

**Issue by juliusvonkohout** [elyra-ai/elyra#2998]
Hello, since a secure S3 storage system has to implement policies instead of giving all users dangerous admin access  i tried the following runtime

```
{
  "display_name": "in-cluster",
  "metadata": {
    "tags": [],
    "display_name": "in-cluster",
    "engine": "Argo",
    "auth_type": "KUBERNETES_SERVICE_ACCOUNT_TOKEN",
    "api_endpoint": "http://ml-pipeline.kubeflow.svc.cluster.local:8888",
    "public_api_endpoint": "https://istio-ingressgateway-istio-system.apps.p028.otc.mcs-paas.io/_/pipeline",
    "cos_auth_type": "USER_CREDENTIALS",
    "cos_endpoint": "http://minio-service.kubeflow.svc.cluster.local:9000",
    "cos_bucket": "mlpipeline",
    "cos_directory_prefix": "private-artifacts/julius-vonkohout",
    "cos_username": "julius-vonkohout",
    "cos_password": "....",
    "runtime_type": "KUBEFLOW_PIPELINES"
  },
  "schema_name": "kfp"
}
```

cos_directory_prefix is being completely ignored. Without admin access it even gets access denied at the bucket level /mlpipeline . This admin level stuff sounds very dangerous to me. Why is it trying to access anything at the root level?

```
Traceback (most recent call last):
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/processor.py", line 481, in _verify_cos_connectivity
    CosClient(runtime_configuration)
  File "/home/lib64/python3.9/site-packages/elyra/util/cos.py", line 117, in __init__
    raise ex from ex
  File "/home/lib64/python3.9/site-packages/elyra/util/cos.py", line 101, in __init__
    if not self.client.bucket_exists(self.bucket):
  File "/home/lib64/python3.9/site-packages/minio/api.py", line 658, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/lib64/python3.9/site-packages/minio/api.py", line 403, in _execute
    return self._url_open(
  File "/home/lib64/python3.9/site-packages/minio/api.py", line 386, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access denied, resource: /mlpipeline, request_id: 1724638951F71DCE, host_id: None, bucket_name: mlpipeline

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lib64/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/handlers.py", line 156, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/processor.py", line 165, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 264, in process
    kfp_argo_compiler.Compiler().compile(pipeline_function, pipeline_path, pipeline_conf=pipeline_conf)
  File "/home/lib64/python3.9/site-packages/kfp/compiler/compiler.py", line 1175, in compile
    self._create_and_write_workflow(
  File "/home/lib64/python3.9/site-packages/kfp/compiler/compiler.py", line 1227, in _create_and_write_workflow
    workflow = self._create_workflow(pipeline_func, pipeline_name,
  File "/home/lib64/python3.9/site-packages/kfp/compiler/compiler.py", line 1005, in _create_workflow
    pipeline_func(*args_list, **kwargs_dict)
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 247, in <lambda>
    pipeline_function = lambda: self._cc_pipeline(  # nopep8 E731
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/kfp/processor_kfp.py", line 509, in _cc_pipeline
    self._verify_cos_connectivity(runtime_configuration)
  File "/home/lib64/python3.9/site-packages/elyra/pipeline/processor.py", line 483, in _verify_cos_connectivity
    raise RuntimeError(
RuntimeError: Error connecting to cloud storage: S3 operation failed; code: AccessDenied, message: Access denied, resource: /mlpipeline, request_id: 1724638951F71DCE, host_id: None, bucket_name: mlpipeline. Update runtime configuration 'in-cluster' and try again.
```

A proper Kubeflow installation does not need to violate company guidelines and common sense https://github.com/kubeflow/pipelines/pull/7725 All of this works properly with normal pipelines, while it fails when using python scripts.

Furthermore i noticed that Elyra base images heavily violate the official Kbernetes restricted podsecuritystandards https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted for no reason. A simple container should not require extremely dangerous root rights.

```
time="2022-11-04T12:56:51.784Z" level=info msg="capturing logs" argo=true
mkdir: cannot create directory ‘./jupyter-work-dir/’: Permission denied
time="2022-11-04T12:56:51.786Z" level=error msg="cannot save artifact /tmp/mlpipeline-metrics.json" argo=true error="stat /tmp/mlpipeline-metrics.json: no such file or directory"
time="2022-11-04T12:56:51.786Z" level=error msg="cannot save artifact /tmp/mlpipeline-ui-metadata.json" argo=true error="stat /tmp/mlpipeline-ui-metadata.json: no such file or directory"
Error: exit status 1
```

Anaconda (2021.11) with Python 3.x
Container Image continuumio/anaconda3:2021.11 was used

**Expected behavior**

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 3.12
 - Installation source: Kubeflow Jupyterlab

**Comment by ptitzler** [comment]
Hi @juliusvonkohout 

### Object prefix

Thanks for reporting! It appears that version 3.12 does have an issue. I ran a quick test on 3.13 (available soon - famous last words) and this seems to work there. 

   ![image](https://user-images.githubusercontent.com/13068832/200659821-61b5cb74-8bb7-42bf-abb6-a37a4df5c1d1.png)

### S3 permissions / admin access

We'll need more time to look into this. Not much has changed in a while but I don't recall that there is a requirement for admin access. Elyra makes the following calls using the minio client library:
 - `client.bucket_exists(bucket)` - check if the user-specified bucket exists (defined in the runtime configuration)
 - `client.make_bucket(bucket)` - try to create the bucket if ^^ returns something other than success
 - `client.client.fput_object(bucket, fq_object_name, local_file_path)` - upload the files to said bucket

### Runtime configuration images

 [updating the comment in a few minutes with details]

**Comment by ptitzler** [comment]
Quick update on 'S3 permissions / admin access':

The following setup worked just fine in our dev environment:

```
$ mc admin user add localminio bert 1234123
$ mc mb localminio/rwbucket
$ mc admin policy add localminio rwbucket read_and_write.json
$ mc admin policy set localminio rwbucket user=bert 
```

read_and_write.json

```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::rwbucket/*"]}]}
```

**Comment by juliusvonkohout** [comment]
1. Does that mean that i can set "cos_directory_prefix": "private-artifacts/julius-vonkohout", in the runtime WITHOUT having to modify the pipeline manually?
2. Alright, i understand your approach with the images. Yes removing insecure images is the right way to go.
3. There will be a redesign of Kubeflows S3 storage in the near future, that enforces proper folder permissions. so you will not be able to just list the root in Kubeflow 1.7 or maybe 1.8. Also something insecure as this {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::rwbucket/*"]}]} will not be possible. you will only have access to your own folder, not he whole bucket (usually mlpipeline). So only the users folder e.g. "s3://mlpipeline/private-artifacts/julius-vonkohout" should be liested and modified. So you should not do anything outside of cos_directory_prefix

**Comment by ptitzler** [comment]
> 1. Does that mean that i can set "cos_directory_prefix": "private-artifacts/julius-vonkohout", in the runtime WITHOUT having to modify the pipeline manually?

No, this is currently only a Elyra pipeline property. There's currently no way to define a "global" default that could be defined in the runtime configuration (where it would apply to all pipelines that are executed using that configuration) or the Elyra pipeline editor (settings apply to all pipelines).

> 3. There will be a redesign of Kubeflows S3 storage in the near future, that enforces proper folder permissions. so you will not be able to just list the root in Kubeflow 1.7 or maybe 1.8. Also something insecure as this {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["s3:_"],"Resource":["arn:aws:s3:::rwbucket/_"]}]} will not be possible. you will only have access to your own folder, not he whole bucket (usually mlpipeline). So only the users folder e.g. "s3://mlpipeline/private-artifacts/julius-vonkohout" should be listed and modified. So you should not do anything outside of cos_directory_prefix

Thanks for the heads-up! I don't think Elyra explicitly queries buckets or tries to read/write objects that don't have the user-defined object prefix included.  The setup you are describing should therefore not be an issue.

**Comment by ptitzler** [comment]
Unrelated to the concerns you've raised, but since this discussion is primarily about security it's probably worth bringing up: I've just noticed that you've configured your runtime to use UID/password for object storage authentication. You should always [utilize secrets](https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html#cloud-object-storage-authentication-type-cos-auth-type) in test/production deployments to prevent exposing the credentials in KFP. By default they are embedded in the DAG.

**Comment by juliusvonkohout** [comment]
> No, this is currently only a Elyra pipeline property. There's currently no way to define a "global" default that could be defined in the runtime configuration (where it would apply to all pipelines that are executed using that configuration) or the Elyra pipeline editor (settings apply to all pipelines).

That is sad to hear. For example using the python script to pipeline functionality will not work then or  it will need manual intervention as soon as only prefixes are allowed. Setting the prefix in the runtime would be a proper solution for that.

**Comment by ptitzler** [comment]
No. This should work for any type of file X (Jupyter notebook, Python/R script) that Elyra's generic component supports. All you need to do is declare the output (files) that file X produces:

![image](https://user-images.githubusercontent.com/13068832/200895053-b57873f8-82ab-46ca-af8c-8305eb66d76b.png)

After file X was executed by the Elyra bootstrapper script, the bootstrapper will try to locate the specified output files and upload them to the object storage bucket using the user-defined prefix. This pre- and post processing is transparent to file X and Kubeflow Pipelines in general. Therefore there is no need for file X to know what the object prefix is, as long as it doesn't try to upload files to object storage directly.

I should mention - because that's a common cause for confusion - that currently these outputs are a 'proprietary' mechanism that generic components use. These outputs are not the same as component outputs that a KFP component definition might declare. Conceptually, this is the generic components signature, which doesn't declare any component inputs or outputs.
```
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: ...
    command: [sh, -c]
    args: ["..."]
```

The metadata that the component requires (such as the output files to be uploaded to object storage) is passed in using the container args.

**Comment by ptitzler** [comment]
3.13. was released https://github.com/elyra-ai/elyra/releases/tag/v3.13.0, which should fix the path prefix issue you've reported.

**Comment by juliusvonkohout** [comment]
> 3.13. was released https://github.com/elyra-ai/elyra/releases/tag/v3.13.0, which should fix the path prefix issue you've reported.

But I guess it will still not allow me to set the runtime specific prefix automatically. We will need a way to set the prefix globally for all pipelines from the python and R editor. We do not need a user defined prefix but instead a runtime defined prefix.

**Comment by ptitzler** [comment]
You are correct. Adding support for a new prefix property in [the runtime configuration](https://elyra.readthedocs.io/en/stable/user_guide/runtime-conf.html), which would apply to all pipelines that are submitted or exported using that configuration, would be a new requirement.
