### ISSUE TITLE
"Unsupported Media Type" error when running a pipeline in Kubeflow

### ISSUE THREAD

**Issue by ozen** [elyra-ai/elyra#3092]
**Describe the issue**
I get an "Unsupported Media Type" http error when sending a request to run a simple pipeline in Kubeflow.
I created a "hello world" Python script, then created a pipeline in KF pipeline editor containing a single python script node for the script. Runtime image is set to Anaconda with Python 3.x, cpu=1 and ram=1. No other properties are modified.
Received the error log below.

**Log output**
<details><summary>Log Output</summary>
<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/kfp/processor_kfp.py", line 347, in process
    kfp_pipeline = client.upload_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/kfp/_client.py", line 1306, in upload_pipeline
    response = self._upload_api.upload_pipeline(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 69, in upload_pipeline
    return self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 163, in upload_pipeline_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 407, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (415)
Reason: Unsupported Media Type
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 27 Jan 2023 19:54:40 GMT', 'Content-Type': 'application/json', 'Content-Length': '55', 'Connection': 'keep-alive', 'Referrer-Policy': 'no-referrer', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block'})
HTTP response body: {"error":"RESTEASY003065: Cannot consume content type"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/handlers.py", line 160, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/processor.py", line 166, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/kfp/processor_kfp.py", line 383, in process
    raise RuntimeError(
RuntimeError: Failed to upload Kubeflow pipeline 'untitled' - Check Kubeflow Pipelines runtime configuration: 'kubeflow'
</pre>
</details>

**Deployment information**
 - Elyra version: 3.14.2
 - Running Elyra as a notebook server in Kubeflow
 - kfp version: 1.8.18

**Pipeline runtime environment**
- Kubeflow Pipelines
- k8s v1.22.6
- Kubeflow v1.6.1
- multi-user auth enabled
 
**Runtime configuration settings**
- api endpoint: https://<my_kf_domain>/pipeline
- user namespace: <my_namespace>
- engine: Argo
- auth type: service account token
- cos endpoint: https://<my_minio_domain>
- bucket name: <my_bucket>
- cos auth type: user credentials
- cos credentials secret: empty
- cos username: <my_username>
- cos password: <my_password>

I think the runtime settings are correct, because if I modify them I get errors such as access denied for kubeflow or minio before getting the http error.

**Comment by ozen** [comment]
I changed the api endpoint in the untime configuration settings in trial and error:
new api endpoint: http://ml-pipeline-ui.kubeflow:80/pipeline

And got a new error:

<details><summary>Log Output</summary>
<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/kfp/processor_kfp.py", line 247, in process
    client.list_experiments(namespace=user_namespace, page_size=1)
  File "/usr/local/lib/python3.8/dist-packages/kfp/_client.py", line 532, in list_experiments
    response = self._experiment_api.list_experiment(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api/experiment_service_api.py", line 567, in list_experiment
    return self.list_experiment_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api/experiment_service_api.py", line 668, in list_experiment_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.8/dist-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Fri, 27 Jan 2023 21:38:56 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '1'})
HTTP response body: RBAC: access denied


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/handlers.py", line 160, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/processor.py", line 166, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elyra/pipeline/kfp/processor_kfp.py", line 254, in process
    raise RuntimeError(
RuntimeError: Failed to `kfp.Client().list_experiments()` against: 'http://ml-pipeline-ui.kubeflow:80/pipeline' - Check Kubeflow Pipelines runtime configuration: 'kubeflow' - [TIP: ensure namespace 'yozen' is correct]
</pre>
</details>

The namespace in the runtime configuration (yozen) is correct and my current user namespace.
To understand what's going on I created a notebook, tried running the following code and received the results in comments:
```python
import kfp
client = kfp.Client(host="http://ml-pipeline-ui.kubeflow:80/pipeline")
client.get_user_namespace()   # output: yozen
client.list_experiments()   # error: access denied
client.list_experiments(namespace="yozen")   # error: access denied
```
I'm not sure if this is the expected behavior or I'm making a mistake.

**Comment by ptitzler** [comment]
Did you check https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/#rbac-authorization?

As a side note, KF 1.6.1 uses KFP v2, which Elyra does not support. Last time we checked (back in 2022) the v2 SDK didn't support all v1 features Elyra is using.

**Comment by ozen** [comment]
I was confused about KFP versioning before, but I think the following points are correct:
- Installating KF 1.6.1 using [manifests](https://github.com/kubeflow/manifests/tree/v1.6.1) installs KFP 2.0.0-alpha.5
- KFP version is not the same with KFP SDK version
- KF 1.6.1 docs still include Pipelines SDK v1 with "stable" marking, but Pipelines SDK v2 with "beta" marking: https://v1-6-branch.kubeflow.org/docs/components/pipelines/
- Updated Roadmap for KF 1.7 includes "Delivery of KFP V2 beta": https://github.com/kubeflow/kubeflow/blob/29e74b13975e5f0729fd731b2df3fcd2beee5690/ROADMAP.md
- kfp Python package versions for SDK v2 are 2.x.x. But 1.8.x are still being released: https://pypi.org/project/kfp/#history

These came from poking around kubeflow repos. A KFP maintainer could simply answer whether SDK v1 still fully works in KF 1.6.1.

I am using kfp (Python package) v1.8.18 in a notebook. 
I had checked the link you provided. I have the PodDefault (created manually) and the token is mounted. 
I have a RoleBinding that assigns `kubeflow-edit` ClusterRole to `default-editor` ServiceAccount in my user namespace (created automatically with Profile)
The sample code using kfp.Client() works in a notebook. `list_experiments` method returns a result. It returns "access denied" when elyra calls it in the same notebook server.

**Comment by ozen** [comment]
I got it working! 
I was using `kfp.Client()` in the notebook so it was automatically setting a hostname. I checked what it is with `client._existing_config.host`. Changed the api endpoint in runtime config from 
`http://ml-pipeline-ui.kubeflow:80/pipeline` 
to
 `http://ml-pipeline.kubeflow.svc.cluster.local:8888` 
and the pipeline run is sent and completed.
I don't know why the change from Pod endpoint to Service URL was necessary since the former is suggested in Elyra docs.

**Comment by ptitzler** [comment]
Excellent! Clever approach to figuring this out. Since there are many ways to configure KFP/Kubernetes, our generic answers in the documentation might not always hit the mark.

Quick follow-up:

> I was confused about KFP versioning before, but I think the following points are correct:
> Installing KF 1.6.1 using [manifests](https://github.com/kubeflow/manifests/tree/v1.6.1) installs KFP 2.0.0-alpha.5
> KFP version is not the same with KFP SDK version

Yes, this is important to note. My apologies, I guess my answer about v2 support wasn't specific enough. Elyra [requires KFP SDK package version < 2.0](https://github.com/elyra-ai/elyra/blob/main/pyproject.toml#L52). So irrespective of which version of Kubeflow/Pipelines you have deployed (v1.x or 2.x) on Kubernetes, Elyra will always use the v1 SDK API to communicate with the server. As long as the Kubeflow server supports this API, you will be able to run pipelines. When we ran a few tests to determine whether Elyra would work with  v2 of the KFP SDK we encountered issues., which caused us to put the upper cap on the package version. As a result, Elyra cannot take advantage of any KFP v2 features.

**Comment by ozen** [comment]
Thanks! I'm closing the issue then.
