### ISSUE TITLE
Can't make runs in elyra2.1.0

### ISSUE THREAD

**Issue by kimkihoon0515** [elyra-ai/elyra#3111]
elyra version : 2.1.0
kfp : 1.3.0
kubeflow pipelines : 2.0.0-alpha3

Here's two ways that I've tried
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/63439911/218741396-a0990430-9fa8-4741-8cd4-e848fc62f48a.png">
and i got 
<img width="983" alt="image" src="https://user-images.githubusercontent.com/63439911/218741534-7115fa8c-e118-400c-a61f-67e8df79bb72.png">

the second way is 
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/63439911/218742086-d6660702-f01a-4482-826a-a152294058fb.png">
and also i got
<img width="986" alt="image" src="https://user-images.githubusercontent.com/63439911/218741953-d1566d1f-4277-457b-afab-b0d47678f212.png">

I' cant put Username & Password because I don't use dex for authentication. 
I'm using keycloak for oidc auth service and it doesn't work for username&passwords.
I used kubernetes service account to authenticate in elyra>=3.0.0 but can't make runs in elyra<3 because service account token seems doesn't work in elyra version 2.

Also I need to make runs in elyra version 1.5.3 so if you guys can add kubernetes service account method or something like that, it would be very helpful to me

**Comment by ptitzler** [comment]
Hi @kimkihoon0515!

> but can't make runs in elyra<3 because service account token seems doesn't work in elyra version 2.
>
> Also I need to make runs in elyra version 1.5.3 so if you guys can add kubernetes service account method or something > like that, it would be very helpful to me

Due to resource constraints we don't add new features or backport features to releases that are older than the "current major release", which is 3.x as of today.

**Comment by kimkihoon0515** [comment]
@ptitzler Then is there no way to make runs if I don't use dex for auth??

**Comment by ptitzler** [comment]
Unfortunately not in releases older than v3

**Comment by kimkihoon0515** [comment]
@ptitzler Thx for the help. One more question. Is there a function to attach volume in runtime images in elyra 1.5.3?? 
If not, then which version of elyra has it??

**Comment by ptitzler** [comment]
No. Volume mount support was [added in version 3.10](https://github.com/elyra-ai/elyra/releases/tag/v3.10.0)

**Comment by kimkihoon0515** [comment]
@ptitzler I am trying to install the elyra v1.5.3 package locally without using pip.
I tried 
```
python setup.py install
```
and got some warnings
```
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.metadata.schemas' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.metadata.schemas' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.metadata.schemas' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.metadata.schemas' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.pipeline.tests.resources.archive' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.pipeline.tests.resources.archive' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.pipeline.tests.resources.archive' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.pipeline.tests.resources.archive' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.pipeline.tests.resources.node_util' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.pipeline.tests.resources.node_util' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.pipeline.tests.resources.node_util' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.pipeline.tests.resources.node_util' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.pipeline.tests.resources.sample_pipelines' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.pipeline.tests.resources.sample_pipelines' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.pipeline.tests.resources.sample_pipelines' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.pipeline.tests.resources.sample_pipelines' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.templates' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.templates' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.templates' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.templates' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!

  check.warn(importable)
/usr/local/lib/python3.8/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'elyra.util.tests' as data is deprecated, please list it in `packages`.
    !!


    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'elyra.util.tests' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'elyra.util.tests' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'elyra.util.tests' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.


!!
```
Do these warnings need to be fixed or does it matter?

**Comment by ptitzler** [comment]
I would expect things to work because the referenced packages are still installed. The only packages that matter at runtime are `elyra.metadata.schemas` and `elyra.templates`. If they are ignored by ,`setuptools` in the future `setup.py` would require changes.

I should note that we've updated the documentation to indicate that Elyra 1.x and 2.x are no longer maintained: https://github.com/elyra-ai/elyra/blob/main/SECURITY.md

**Comment by kimkihoon0515** [comment]
@ptitzler so you mean what I have to do is clone the repo and run `make install`?

**Comment by ptitzler** [comment]
Yes. The relevant build and installation documentation for the version you are using is [here](https://elyra.readthedocs.io/en/v1.5.3/developer_guide/development-workflow.html) and [here](https://elyra.readthedocs.io/en/v1.5.3/getting_started/installation.html). Note that the build/installation process is significantly different from the one used in more current releases. The last time we've built this version of Elyra was in January 2021.

**Comment by kimkihoon0515** [comment]
@ptitzler Got an error when running `make install`
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
flake8 elyra
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/finder.py", line 291, in _load_plugin
    obj = plugin.entry_point.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/hacking/core.py", line 185
    except ImportError, exc:
                      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File "/usr/local/lib/python3.8/dist-packages/flake8/options/parse_args.py", line 42, in parse_args
    plugins = finder.load_plugins(raw_plugins, plugin_opts)
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/finder.py", line 365, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/finder.py", line 307, in _import_plugins
    return [_load_plugin(p) for p in plugins]
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/finder.py", line 307, in <listcomp>
    return [_load_plugin(p) for p in plugins]
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/finder.py", line 293, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "hacking" due to invalid syntax (core.py, line 185).
make: *** [Makefile:72: lint-server] Error 1
```
any solution for this?? 
I have flake8 version 6.0.0 and hacking version 0.5.4

**Comment by ptitzler** [comment]
I can confirm that this legacy branch doesn't build anymore in a clean environment. As I've mentioned earlier, this release is no longer supported and we therefore won't take any actions trying to resolve the issue.
