### ISSUE TITLE
[Windows] Error with git extension on startup

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#319]
When starting elyra on Windows, the user token is displayed and startup looks fine, but then it produces the following traceback information, which I assume is related to the git extension:
```
[E 16:02:23.527 LabApp] Uncaught exception POST /git/show_top_level?1583280143512 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/show_top_level?1583280143512', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\programdata\anaconda3\envs\elyra\lib\site-packages\tornado\web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\programdata\anaconda3\envs\elyra\lib\site-packages\jupyterlab_git\handlers.py", line 89, in post
        result = self.git.show_top_level(current_path)
      File "c:\programdata\anaconda3\envs\elyra\lib\site-packages\jupyterlab_git\git.py", line 493, in show_top_level
        cwd=os.path.join(self.root_dir, current_path),
      File "c:\programdata\anaconda3\envs\elyra\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "c:\programdata\anaconda3\envs\elyra\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 16:02:23.566 LabApp] Unhandled error
[E 16:02:23.580 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "19",
      "Authorization": "token c41be100e1e9ae6360ae09be2039d6938cca5b81b9b0f0e4",
      "Sec-Fetch-Dest": "empty",
      "X-Xsrftoken": "2|5ad4e958|fd1a3c42f5498cbd37d98f0a94e0f073|1583274730",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|5ad4e958|fd1a3c42f5498cbd37d98f0a94e0f073|1583274730; username-localhost-8888=\"2|1:0|10:1583280143|23:username-localhost-8888|44:Y2RhOTg5ZjlmZWU3NDhkNWI2OWQ5MzJjYmQ0ZGRmODY=|918d3fc380fe2ab25f869d3d63dee2d212439fec258425375c72347ec7857513\""
    }
[E 16:02:23.581 LabApp] 500 POST /git/show_top_level?1583280143512 (::1) 63.01ms referer=http://localhost:8888/lab
```

**Comment by lresende** [comment]
Have been using the latest version of Elyra on windows with git without issues

![image](https://user-images.githubusercontent.com/382917/133535902-2c3fd72d-7d7c-4a00-bfcc-57497b52f26e.png)
