### ISSUE TITLE
Issue running with Pandas image "kernel_manager_class’"

### ISSUE THREAD

**Issue by yil532** [elyra-ai/elyra#437]
While running my pipeline under pandas image. It says KeyError: ‘kernel_manager_class’. Could someone please help me?
Here is the error message
```
`Parsing Arguments.....
Get file Part 1 - Data Cleaning-404fc2a7-8fde-4e45-9652-55bcd230916b.tar.gz from bucket yil532
TAR Archive pulled from Object Storage.
Unpacking........
Unpacking Complete.
Executing notebook through Papermill: Part 1 - Data Cleaning.ipynb ==> Part 1 - Data Cleaning_output.ipynb

Executing:   0%|          | 0/47 [00:00<?, ?cell/s]
Executing:   0%|          | 0/47 [00:00<?, ?cell/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_manager_class'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "bootstrapper.py", line 145, in <module>
    kernel_name="python3"
  File "/usr/local/lib/python3.7/site-packages/papermill/execute.py", line 106, in execute_notebook
    **engine_kwargs
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/usr/local/lib/python3.7/site-packages/papermill/clientwrap.py", line 36, in execute
    with self.setup_kernel(**kwargs):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 401, in setup_kernel
    self.start_kernel_manager()
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 328, in start_kernel_manager
    self.km = self.kernel_manager_class(kernel_name=self.kernel_name, config=self.config)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 240, in _kernel_manager_class_default
    from jupyter_client import AsyncKernelManager
ImportError: cannot import name 'AsyncKernelManager' from 'jupyter_client' (/usr/local/lib/python3.7/site-packages/jupyter_client/__init__.py)`
```

**Comment by kjdoyle** [comment]
To workaround this issue I added to the first cell of my notebook:

!pip install PyGithub pandas > /dev/null 2>&1

And used the tensorflow 1.12.3 deep learning framework option instead of panadas.

**Comment by yil532** [comment]
Thank you for helping! That works for me! @kjdoyle

**Comment by lresende** [comment]
Thanks @kjdoyle and @yil532. I leave this open for a little while to remind us that we need to help fix the original issue on the pandas community image or move to a recent one if it's already fixed.

**Comment by kevin-bates** [comment]
The immediate issue here is that the `nbclient` installed by `papermill` wants a newer version of `jupyter_client` than what is installed.  This is part of a bigger issue with how `kfp-notebook` is attempting to update packages and `jupyter_client` is not getting updated as expected.

**Comment by lresende** [comment]
I started having a similar issue trying to bring up anaconda image and the source of the problem is that our kfp bootstrap script needs to update the jupyter client dependency. I will fix that on kfp-notebook.
