### ISSUE TITLE
Cleanup build of jupyterlab extensions

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#501]
We have made a few workaround (and extra steps) on Elyra build to workaround some pre-existent build issues on Jupyterlab 1.x that were preventing updates of linked packages with same version, but are now resolved on JupyterLab 2.x:

Some of the changes (as I recall) are related to:
* Yarn cache clean
* Uninstall / Install of Elyra packages
* Multiple JupyterLab clean/builds

A validation test after any proposed changes would be to
* Start from a clean environment (clean-jupyterlab.sh)
* Build Elyra
* Make a change on Application package
* Build Elyra and make sure Application package has the new contents

**Comment by lresende** [comment]
Related issue #375, that could be handled together.

**Comment by ajbozarth** [comment]
I opened #502 to handle #375 and update our packages to link instead of install. This address some of the issues raised here. That PR does not handle any removal of extraneous cleaning that was added due to the use of install instead of link.

**Comment by ajbozarth** [comment]
Note: I assigned myself since I'm partially working on this but others can feel free to address other parts

**Comment by vabarbosa** [comment]
@ajbozarth i could assist here. any specific part i should start with?

**Comment by ajbozarth** [comment]
I would look at if we can remove any steps, such as "cleaning" steps outside the clean target in Makefile

**Comment by vabarbosa** [comment]
waiting for PRs #502 and #505 (which currently have changes to `Makefile`) to get merged in then i can look more in depth at this. but from a quick read though, a couple possible considerations:

- remove `rm -f yarn.lock package-lock.json` in the **yarn-install** as it's already captured in **clean**
- move `yarn cache clean` to **clean** instead of  **yarn-install** if goal is to keep all the clean scripts in same target
- replace `yarn cache clean` with `rm -rf $(yarn cache dir)` as native `rm` should be faster than `rimraf` (that yarn clean is running)
- **lint-ui** (which runs `yarn run prettier` & `yarn run eslint`) is called after the extensions have been packaged. should it not be before packaging up extensions? fyi, this is addressed in #502 (where packaging extensions is moved to a separate **npm-dists** that should only be called when publishing a release)


(related to #177)

**Comment by lresende** [comment]
After some investigation, here are some more details that I discovered:

Steps done:
0-create a new local branch and change the branch version to a non-existing release
1-build elyra
2-clean-jupyterlab.sh
3-cp /Users/lresende/opensource/elyra/elyra/dist/elyra*.tgz /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab/extensions

```
jupyter labextension list
JupyterLab v2.1.2
Known labextensions:
   app dir: /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab
        @elyra/application v0.12.0  enabled  OK
        @elyra/code-snippet-extension-experimental v0.12.0  enabled  OK
        @elyra/pipeline-editor-extension v0.12.0  enabled  OK
        @elyra/python-runner-extension v0.12.0  enabled  OK
        @elyra/theme-extension v0.12.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @elyra/python-runner-extension needs to be included in build
    @elyra/pipeline-editor-extension needs to be included in build
    @elyra/theme-extension needs to be included in build
    @elyra/code-snippet-extension-experimental needs to be included in build
```

When all Elyra npm packages are scheduledd to deploy, it complains about application not in npm
When only Application npm package is available, it works fine, and `jupyterlab build` works ok
After Application is installed, then trying to install other Elyra packages result in:
```
An error occured.
RuntimeError: npm dependencies failed to install
```
Trying to install only python runner works
Trying to install Application and python runner also works
Code-snippet, Pipeline, and theme fails with the error above


As for the build log when it fails:
```
[LabBuildApp] Searching ['/Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab/extensions', '/Users/lresende/.jupyter', '/Users/lresende/opt/anaconda/envs/dev/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /Users/lresende/opt/anaconda/envs/dev/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /Users/lresende/.jupyter
[LabBuildApp] Looking for jupyter_config in /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab/extensions
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /Users/lresende/opt/anaconda/envs/dev/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /Users/lresende/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab/extensions
[LabBuildApp] JupyterLab 2.1.2
[LabBuildApp] Building in /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab
[LabBuildApp] Node v12.13.1

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
\[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find any versions for "@elyra/application" that matches "^0.12.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /var/folders/br/fh9knw197l3899rkb_lrybxm0000gn/T/jupyterlab-debug-nqxwqize.log
[LabBuildApp] Exiting application: JupyterLab
(dev) [lresende@lresende-ibm-2019 extensions]$ more /var/folders/br/fh9knw197l3899rkb_lrybxm0000gn/T/jupyterlab-debug-nqxwqize.log
[LabBuildApp] Building in /Users/lresende/opt/anaconda/envs/dev/share/jupyter/lab
[LabBuildApp] Node v12.13.1

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find any versions for "@elyra/application" that matches "^0.12.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/Users/lresende/opt/anaconda/envs/dev/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by ajbozarth** [comment]
That matches my findings. Essentially jupyter lab only allows non-extension packages to be linked, not installed. Since links must point to a dir and not a tar (unlike installs) the jupyter lab build does not pick it up in the extensions dir when the wheel places it there. So when lab is built it wont find a linked package and will look up the package on npm.

After reading through this again I do have one last idea. For the wheel to somehow unpack the tar'd application lib directory somewhere and link it to lab. But even if that's wasn't super hack-y, I'm not sure it could be done.

**Comment by lresende** [comment]
@ajbozarth My question is, why Application + Python Runner works? And when we start adding the other extensions, it fails.

**Comment by ajbozarth** [comment]
Because python runner doesn't depend on application
