### ISSUE TITLE
Notebook pipelines: support directories and wildcards as "output files"

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#654]
Before a notebook is executed it might not be known what the exact file names are that a notebook generates and wishes to make available to subsequent notebooks. Testing 1.0.0 Beta it appears that currently wildcards or directories are not supported as "Output Files" values.

Example scenario:
- The first (generic) notebook downloads a compressed archive, extracts the content, processes it and stores the resulting X data files in a well known location, e.g. `data/`. How many data files are being produced is not known ahead of time.
- As a user I currently cannot define the "Output Files" that I want to share with subsequent notebooks  because wildcards (e.g. `data/*`) and directory names (e.g. `data/` or `data`) cause a post-processing error, such as 

```
Uploading file data/* as data/* to bucket ptitzler
Unexpected error: <class 'FileNotFoundError'>
Converting from ipynb to html....
Uploading Errored Notebook back to Object Storage
Uploading file load_data-output.ipynb as load_data.ipynb to bucket ptitzler
Uploading file load_data.html as load_data.html to bucket ptitzler
Traceback (most recent call last):
  File "bootstrapper.py", line 219, in <module>
    put_file_to_object_storage(cos_client, input_params['cos-bucket'], file)
  File "bootstrapper.py", line 146, in put_file_to_object_storage
    file_path=file_to_upload)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 696, in fput_object
    with open(file_path, 'rb') as file_data:
FileNotFoundError: [Errno 2] No such file or directory: 'data/*'
```

**Comment by kevin-bates** [comment]
This was fixed by #702.

**Comment by ptitzler** [comment]
@kevin-bates I am still able to reproduce the behavior using 1.0.0.rc2.

**Comment by ptitzler** [comment]
log file:
```
Get file load_data-1b2fc3fa-2b94-4ad8-8caa-c650e5440f62.tar.gz from bucket ptitzler
Processing dependencies........
TAR Archive pulled from Object Storage.
Unpacking........
Unpacking Complete.
Executing notebook through Papermill: load_data.ipynb ==> load_data-output.ipynb
Converting from ipynb to html....
Uploading Result Notebook back to Object Storage
Uploading file load_data-output.ipynb as load_data.ipynb to bucket ptitzler
Uploading file load_data.html as load_data.html to bucket ptitzler
Processing outputs........
Uploading file data/noaa-weather-data-jfk-airport/* as data/noaa-weather-data-jfk-airport/* to bucket ptitzler
Unexpected error: <class 'FileNotFoundError'>
Converting from ipynb to html....
Uploading Errored Notebook back to Object Storage
Uploading file load_data-output.ipynb as load_data.ipynb to bucket ptitzler
Uploading file load_data.html as load_data.html to bucket ptitzler
```

**Comment by kevin-bates** [comment]
I'm sorry @ptitzler - I was thinking _dependencies_ and _inputs_, not _outputs_.  You're correct in re-opening.

**Comment by kevin-bates** [comment]
This will be addressed in the kfp-notebook repo, transferring now.
