### ISSUE TITLE
UI tests appear to be failing intermittently

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#675]
PR #673 failed on py3.6 (but was successful on my repo, although a subsequent retry succeeded so I couldn't get a link) and a [PR from yesterday failed on py3.7](https://github.com/kevin-bates/elyra/runs/799859534) after merging into master and pushing to my repo following a rebase.  

I did happen to find this [PR had failed on py3.8](https://github.com/elyra-ai/elyra/runs/788875488) - so all 3 pythons have been involved and the failure looks like the previous two.  As a result, it doesn't appear to be python-version-specific.

Here's what appears to be the most useful information from the failure.  Since GHActions doesn't appear to keep a build history very well, I thought it might be helpful to capture this here...
```
  8 passing (22s)
  1 failing

  1) PythonEditor
       close python editor:
     CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.

`<div class="jp-icon-hover lm-TabBar-tabCloseIcon fvaq30">...</div>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.get()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
      at Object.ensureAttached (http://localhost:8888/__cypress/runner/cypress_runner.js:155415:24)
      at runAllChecks (http://localhost:8888/__cypress/runner/cypress_runner.js:144560:12)
      at retryActionability (http://localhost:8888/__cypress/runner/cypress_runner.js:144619:16)
      at tryCatcher (http://localhost:8888/__cypress/runner/cypress_runner.js:10161:23)
      at Function.Promise.attempt.Promise.try (http://localhost:8888/__cypress/runner/cypress_runner.js:7435:29)
      at tryFn (http://localhost:8888/__cypress/runner/cypress_runner.js:158641:24)
      at whenStable (http://localhost:8888/__cypress/runner/cypress_runner.js:158682:12)
      at http://localhost:8888/__cypress/runner/cypress_runner.js:158205:16
      at tryCatcher (http://localhost:8888/__cypress/runner/cypress_runner.js:10161:23)
      at Promise._settlePromiseFromHandler (http://localhost:8888/__cypress/runner/cypress_runner.js:8096:31)
      at Promise._settlePromise (http://localhost:8888/__cypress/runner/cypress_runner.js:8153:18)
      at Promise._settlePromise0 (http://localhost:8888/__cypress/runner/cypress_runner.js:8198:10)
      at Promise._settlePromises (http://localhost:8888/__cypress/runner/cypress_runner.js:8278:18)
      at Promise._fulfill (http://localhost:8888/__cypress/runner/cypress_runner.js:8222:18)
      at http://localhost:8888/__cypress/runner/cypress_runner.js:9836:46
  From Your Spec Code:
      at Context.eval (http://localhost:8888/__cypress/tests?p=tests/integration/pythoneditor.ts:122:51)
```

**Comment by kevin-bates** [comment]
@marthacryan @ajbozarth - This just happened for [py3.7](https://github.com/elyra-ai/elyra/pull/589/checks?check_run_id=812261658) and [py3.8](https://github.com/elyra-ai/elyra/pull/589/checks?check_run_id=812261673) during the CI of #589.

**Comment by kevin-bates** [comment]
Here's another, but relative to [py3.6](https://github.com/kevin-bates/elyra/runs/823636870?check_suite_focus=true) this time.
I'll stop adding these now.
