### ISSUE TITLE
Pipeline validation should include a check that notebook file exists

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#815]
This is partially related to #608.  When an existing pipeline is used from a different notebook root directory (i.e., the location from where the jupyter server was started or where it's `--notebook-dir` option is pointing), none of the notebooks referenced within the pipeline will be correct.  Double-clicking on the node to launch the notebook does nothing in the UI, but produces the following on the notebook server console:
```
[W 10:20:49.936 LabApp] 404 GET /api/contents/notebooks/demographics_us_data.ipynb?content=0&1596561649931 (::1): No such file or directory: notebooks/demographics_us_data.ipynb
[W 10:20:49.936 LabApp] No such file or directory: notebooks/demographics_us_data.ipynb
```
Since all dependencies of a given node (i.e., notebook) are directly correlated to the notebook's location, attempts to run such a pipeline ultimately result in failures to handle those dependencies.
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 220, in _cc_pipeline
    dependency_archive_path = self._generate_dependency_archive(operation)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 275, in _generate_dependency_archive
    require_complete=True)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/util/archive.py", line 119, in create_temp_archive
    tar.add(source_dir, arcname="", filter=tar_filter)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/tarfile.py", line 1928, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/tarfile.py", line 1807, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kbates/notebooks/notebooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 118, in export
    kfp.compiler.Compiler().compile(pipeline_function, absolute_pipeline_export_path)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 926, in compile
    allow_telemetry=allow_telemetry)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 983, in _create_and_write_workflow
    allow_telemetry)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/kfp/compiler/compiler.py", line 806, in _create_workflow
    pipeline_func(*args_list)
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 116, in <lambda>
    pipeline_function = lambda: self._cc_pipeline(pipeline, pipeline_name)  # nopep8
  File "/opt/anaconda3/envs/elyra-dev/lib/python3.7/site-packages/elyra/pipeline/processor_kfp.py", line 238, in _cc_pipeline
    format(operation.name, ex))
FileNotFoundError: Node 'demographics_us_data' referenced dependencies that were not found: [Errno 2] No such file or directory: '/Users/kbates/notebooks/notebooks'
```
However, if we flag the notebook location issues as invalid, the user has no recourse because the notebook field isn't editable.

**Comment by lresende** [comment]
I think this is also related to #204, and the notebook should be treated as any dependency which should be valid at the time of submission.

**Comment by lresende** [comment]
But we need this, on the front end as well.

**Comment by ajbozarth** [comment]
I'm bringing this under the umbrella of #833 to handle validating the existence of node files in a pipeline
