### ISSUE TITLE
[Docker] pipeline execution fails with KeyError: 'kernel_manager_class'

### ISSUE THREAD

**Issue by ptitzler** [elyra-ai/elyra#920]
- Run (latest = 1.1.0) 

  ```
  docker run -it -p 8888:8888 elyra/elyra:dev jupyter lab --debug
  ```

  ```
  docker run -it -p 8888:8888 elyra/elyra:latest jupyter lab --debug
  ```

- Open the displayed URL in the browser
- Clone the https://github.com/elyra-ai/examples.git repository into the JL work directory
- Open the NOAA pipeline
- Run the pipeline locally

The log contains the following error

```
Executing:   0%|                                                                         | 0/8 [00:00<?, ?cell/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_manager_class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/cli.py", line 238, in papermill
    execution_timeout=execution_timeout,
  File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 106, in execute_notebook
    **engine_kwargs
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 43, in execute
    with self.setup_kernel(**kwargs):
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 430, in setup_kernel
    self.km = self.create_kernel_manager()
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 341, in create_kernel_manager
    self.km = self.kernel_manager_class(kernel_name=self.kernel_name, config=self.config)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 233, in _kernel_manager_class_default
    from jupyter_client import AsyncKernelManager
ImportError: cannot import name 'AsyncKernelManager' from 'jupyter_client' (/opt/conda/lib/python3.7/site-packages/jupyter_client/__init__.py)
[E 20:06:40.793 LabApp] Internal error executing /home/jovyan/work/examples/pipelines/dax_noaa_weather_data/load_data.ipynb
[E 20:06:40.794 LabApp] Uncaught exception POST /elyra/pipeline/schedule?1599682000126 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/elyra/pipeline/schedule?1599682000126', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 76, in _execute_operation
        subprocess.run(argv, env=envs, check=True)
      File "/opt/conda/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['papermill', '/home/jovyan/work/examples/pipelines/dax_noaa_weather_data/load_data.ipynb', '/home/jovyan/work/examples/pipelines/dax_noaa_weather_data/load_data.ipynb', '--cwd', '/home/jovyan/work/examples/pipelines/dax_noaa_weather_data']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
        response = await PipelineProcessorManager.instance().process(pipeline)
      File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 70, in process
        res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
      File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 55, in process
        self._execute_operation(operation)
      File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 79, in _execute_operation
        raise RuntimeError(f'Internal error executing {filepath}') from ex
    RuntimeError: Internal error executing /home/jovyan/work/examples/pipelines/dax_noaa_weather_data/load_data.ipynb

```

**Comment by ptitzler** [comment]
Same problem for `:dev` tag.

**Comment by ptitzler** [comment]
See https://github.com/elyra-ai/elyra/issues/619
