### ISSUE TITLE
Error Processing operation (notebook name)

### ISSUE THREAD

**Issue by sleepo-chin** [elyra-ai/elyra#961]
I do jupyter-hub connect with elyra and elyra connect to enterprise gateway
- elyra 1.1.0 or anything else (i'm not remember it)
- not use kubeflow

Before I change the kernel of notebook. That notebook is no kernel.
If I opened notebook and select my kernel on enterprise gateway such as tensorflow kernel.

so I run pipeline agian. This is a error for me:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 151, in process
    subprocess.run(argv, cwd=file_dir, env=envs, check=True)
  File "/opt/conda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['papermill', '/home/jovyan/work/Untitled.ipynb', '/home/jovyan/work/Untitled.ipynb', '--cwd', '/home/jovyan/work']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 70, in process
    operation_processor.process(operation)
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 154, in process
    raise RuntimeError(f'Internal error executing {filepath}') from ex
RuntimeError: Internal error executing /home/jovyan/work/Untitled.ipynb

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor.py", line 69, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/elyra/pipeline/processor_local.py", line 72, in process
    raise RuntimeError(f'Error processing operation {operation.name}.') from ex
RuntimeError: Error processing operation Untitled.
```

In the logs of jupyter lab said me that no kernel name tensorflow, but I can use a kernel tensorflow for run notebook.

I want to know how to fix that for kernels on enterprise gateway for run pipeline on locally
Thank for your answer.

**Comment by lresende** [comment]
While we look into this issue,  an immediate workaround would be to change the kernel to a local `Python 3` kernel.

**Comment by lresende** [comment]
@sleepo-chin Based on our investigation and some discussion around the team, this seems to be a sort of deep issue on how we run pipelines locally, but the good news is that we have a possible solution that we are working on and will keep you updated via this issue. Anyway, thanks for trying Elyra and we will let you know when a pull request is available.

**Comment by lresende** [comment]
@sleepo-chin This is now on Elyra 1.3.x release, please let us know if you see any other issues related to this.
